# Copyright (C) 2026 g10 Code GmbH
# SPDX-License-Identifier: CC0-1.0
[Paths]
Prefix = ../
# Note: The comma-separated list of Plugins must be quoted as single string for our patched Qt 5
Plugins = "plugins,lib/plugins"
