# inst-oxygen-icons.nsi - Snippet for oxygen-icons.   -*- coding: latin-1; -*-
# Copyright (C) 2005, 2007 g10 Code GmbH
# 
# This file is part of GPG4Win.
# 
# GPG4Win is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# GPG4Win is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA


!ifdef prefix
!undef prefix
!endif
!define prefix ${ipdir}/oxygen-icons-${gpg4win_pkg_oxygen_icons_version}

!ifdef DEBUG
Section "oxygen-icons" SEC_oxygen_icons
!else
Section "-oxygen-icons" SEC_oxygen_icons
!endif
  SetOutPath "$INSTDIR"
!ifdef SOURCES
  File "${gpg4win_pkg_oxygen_icons_src}"
!else

  SetOutPath "$INSTDIR\share\icons\oxygen\16x16\actions"

  File ${prefix}/share/icons/oxygen/16x16/actions/1day.png
  File ${prefix}/share/icons/oxygen/16x16/actions/5days.png
  File ${prefix}/share/icons/oxygen/16x16/actions/7days.png
  File ${prefix}/share/icons/oxygen/16x16/actions/abentry.png
  File ${prefix}/share/icons/oxygen/16x16/actions/alarmclock.png
  File ${prefix}/share/icons/oxygen/16x16/actions/application-exit.png
  File ${prefix}/share/icons/oxygen/16x16/actions/archive-extract.png
  File ${prefix}/share/icons/oxygen/16x16/actions/archive-insert-directory.png
  File ${prefix}/share/icons/oxygen/16x16/actions/archive-insert.png
  File ${prefix}/share/icons/oxygen/16x16/actions/archive-remove.png
  File ${prefix}/share/icons/oxygen/16x16/actions/arrow-down-double.png
  File ${prefix}/share/icons/oxygen/16x16/actions/arrow-down.png
  File ${prefix}/share/icons/oxygen/16x16/actions/arrow-left-double.png
  File ${prefix}/share/icons/oxygen/16x16/actions/arrow-left.png
  File ${prefix}/share/icons/oxygen/16x16/actions/arrow-right-double.png
  File ${prefix}/share/icons/oxygen/16x16/actions/arrow-right.png
  File ${prefix}/share/icons/oxygen/16x16/actions/arrow-up-double.png
  File ${prefix}/share/icons/oxygen/16x16/actions/arrow-up.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-charging-000.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-charging-020.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-charging-040.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-charging-060.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-charging-080.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-charging-100.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-discharging-000.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-discharging-020.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-discharging-040.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-discharging-060.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-discharging-080.png
  File ${prefix}/share/icons/oxygen/16x16/actions/battery-discharging-100.png
  File ${prefix}/share/icons/oxygen/16x16/actions/book.png
  File ${prefix}/share/icons/oxygen/16x16/actions/book2.png
  File ${prefix}/share/icons/oxygen/16x16/actions/bookmark-new-list.png
  File ${prefix}/share/icons/oxygen/16x16/actions/bookmark-new.png
  File ${prefix}/share/icons/oxygen/16x16/actions/bookmark-toolbar.png
  File ${prefix}/share/icons/oxygen/16x16/actions/bookmark.png
  File ${prefix}/share/icons/oxygen/16x16/actions/browser-go.png
  File ${prefix}/share/icons/oxygen/16x16/actions/calendar-today.png
  File ${prefix}/share/icons/oxygen/16x16/actions/camera-test.png
  File ${prefix}/share/icons/oxygen/16x16/actions/cd-data.png
  File ${prefix}/share/icons/oxygen/16x16/actions/cd.png
  File ${prefix}/share/icons/oxygen/16x16/actions/cdburn.png
  File ${prefix}/share/icons/oxygen/16x16/actions/cdcopy.png
  File ${prefix}/share/icons/oxygen/16x16/actions/character-set.png
  File ${prefix}/share/icons/oxygen/16x16/actions/checkmark-korganizer.png
  File ${prefix}/share/icons/oxygen/16x16/actions/chronometer.png
  File ${prefix}/share/icons/oxygen/16x16/actions/clear-left.png
  File ${prefix}/share/icons/oxygen/16x16/actions/color-fill.png
  File ${prefix}/share/icons/oxygen/16x16/actions/color-line.png
  File ${prefix}/share/icons/oxygen/16x16/actions/color-picker.png
  File ${prefix}/share/icons/oxygen/16x16/actions/commandprompt.png
  File ${prefix}/share/icons/oxygen/16x16/actions/configure-shortcuts.png
  File ${prefix}/share/icons/oxygen/16x16/actions/configure-toolbars.png
  File ${prefix}/share/icons/oxygen/16x16/actions/configure.png
  File ${prefix}/share/icons/oxygen/16x16/actions/connect-no.png
  File ${prefix}/share/icons/oxygen/16x16/actions/connection-established.png
  File ${prefix}/share/icons/oxygen/16x16/actions/contact-new.png
  File ${prefix}/share/icons/oxygen/16x16/actions/contact.png
  File ${prefix}/share/icons/oxygen/16x16/actions/datashow.png
  File ${prefix}/share/icons/oxygen/16x16/actions/datashowchart.png
  File ${prefix}/share/icons/oxygen/16x16/actions/decrypted.png
  File ${prefix}/share/icons/oxygen/16x16/actions/dialog-apply.png
  File ${prefix}/share/icons/oxygen/16x16/actions/dialog-cancel.png
  File ${prefix}/share/icons/oxygen/16x16/actions/dialog-close.png
  File ${prefix}/share/icons/oxygen/16x16/actions/dialog-ok-apply.png
  File ${prefix}/share/icons/oxygen/16x16/actions/dialog-ok.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-decrypt.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-encrypt.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-export.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-import.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-new.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-open-folder.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-open-recent.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-open-remote.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-open.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-preview-archive.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-print-frame.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-print-preview.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-print.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-properties.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-revert.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-save-all.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-save-as.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-save.png
  File ${prefix}/share/icons/oxygen/16x16/actions/document-start-presentation.png
  File ${prefix}/share/icons/oxygen/16x16/actions/documentinfo-koffice.png
  File ${prefix}/share/icons/oxygen/16x16/actions/domtreeviewer.png
  File ${prefix}/share/icons/oxygen/16x16/actions/draw-brush.png
  File ${prefix}/share/icons/oxygen/16x16/actions/draw-eraser.png
  File ${prefix}/share/icons/oxygen/16x16/actions/draw-freehand.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-add.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-clear-history.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-clear-list.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-clear-locationbar-rtl.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-clear-locationbar.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-clear.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-copy.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-cut.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-delete-mail.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-delete-shred.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-delete.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-find-mail.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-find-next.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-find-previous.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-find-user.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-find.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-paste.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-redo.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-rename.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-select-all.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-trash.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-undo.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit-user.png
  File ${prefix}/share/icons/oxygen/16x16/actions/edit.png
  File ${prefix}/share/icons/oxygen/16x16/actions/editinput.png
  File ${prefix}/share/icons/oxygen/16x16/actions/emptytrash.png
  File ${prefix}/share/icons/oxygen/16x16/actions/encrypted.png
  File ${prefix}/share/icons/oxygen/16x16/actions/eraser.png
  File ${prefix}/share/icons/oxygen/16x16/actions/exec.png
  File ${prefix}/share/icons/oxygen/16x16/actions/favorites.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fileview-close-left.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fileview-close-right.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fileview-column.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fileview-detailed.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fileview-icon.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fileview-multicolumn.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fileview-preview.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fileview-split.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fileview-text.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fill.png
  File ${prefix}/share/icons/oxygen/16x16/actions/find-next.png
  File ${prefix}/share/icons/oxygen/16x16/actions/find-previous.png
  File ${prefix}/share/icons/oxygen/16x16/actions/flag-black.png
  File ${prefix}/share/icons/oxygen/16x16/actions/flag-blue.png
  File ${prefix}/share/icons/oxygen/16x16/actions/flag-green.png
  File ${prefix}/share/icons/oxygen/16x16/actions/flag-red.png
  File ${prefix}/share/icons/oxygen/16x16/actions/flag-yellow.png
  File ${prefix}/share/icons/oxygen/16x16/actions/flag.png
  File ${prefix}/share/icons/oxygen/16x16/actions/folder-new.png
  File ${prefix}/share/icons/oxygen/16x16/actions/footprint.png
  File ${prefix}/share/icons/oxygen/16x16/actions/fork.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-font-size-less.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-font-size-more.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-indent-less.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-indent-more.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-justify-center.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-justify-fill.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-justify-left.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-justify-right.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-line-spacing-double.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-line-spacing-normal.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-line-spacing-triple.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-list-ordered.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-list-unordered.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-text-bold.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-text-direction-ltr.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-text-direction-rtl.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-text-italic.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-text-strikethrough.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-text-subscript.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-text-superscript.png
  File ${prefix}/share/icons/oxygen/16x16/actions/format-text-underline.png
  File ${prefix}/share/icons/oxygen/16x16/actions/frame-edit.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-config-background.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-config-board.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-config-custom.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-config-options.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-config-theme.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-config-tiles.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-difficult.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-endturn.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-highscores.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-hint.png
  File ${prefix}/share/icons/oxygen/16x16/actions/games-solve.png
  File ${prefix}/share/icons/oxygen/16x16/actions/gear.png
  File ${prefix}/share/icons/oxygen/16x16/actions/get-hot-new-stuff.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-bottom.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-down.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-first-rtl.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-first.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-home.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-jump-locationbar.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-jump-today.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-jump.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-last-rtl.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-last.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-next-rtl.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-next.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-previous-rtl.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-previous.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-top.png
  File ${prefix}/share/icons/oxygen/16x16/actions/go-up.png
  File ${prefix}/share/icons/oxygen/16x16/actions/halfencrypted.png
  File ${prefix}/share/icons/oxygen/16x16/actions/help-about-kde.png
  File ${prefix}/share/icons/oxygen/16x16/actions/help-about.png
  File ${prefix}/share/icons/oxygen/16x16/actions/help-contents.png
  File ${prefix}/share/icons/oxygen/16x16/actions/help-contextual.png
  File ${prefix}/share/icons/oxygen/16x16/actions/history-clear.png
  File ${prefix}/share/icons/oxygen/16x16/actions/history-kdeprint.png
  File ${prefix}/share/icons/oxygen/16x16/actions/history.png
  File ${prefix}/share/icons/oxygen/16x16/actions/images-display.png
  File ${prefix}/share/icons/oxygen/16x16/actions/inktube.png
  File ${prefix}/share/icons/oxygen/16x16/actions/insert-image.png
  File ${prefix}/share/icons/oxygen/16x16/actions/insert-table.png
  File ${prefix}/share/icons/oxygen/16x16/actions/insert-text.png
  File ${prefix}/share/icons/oxygen/16x16/actions/java-kjava.png
  File ${prefix}/share/icons/oxygen/16x16/actions/java.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kdeprint-addprinter.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kdeprint-addpseudo.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kdeprint-enableprinter-kdeprint.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kdeprint-printer-infos.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kdeprint-queuestate-kdeprint.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kdeprint-stopprinter-kdeprint.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kdeprint-testprinter.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-export-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-identity-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-import-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-info-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-key1-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-key1-kopete.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-key2-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-key2-kopete.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-key3-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-key3-kopete.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-key4-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-sign-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kgpg-term-kgpg.png
  File ${prefix}/share/icons/oxygen/16x16/actions/knewstuff.png
  File ${prefix}/share/icons/oxygen/16x16/actions/knotes-delete-knotes.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kontact-contacts.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kontact-date.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kontact-journal.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kontact-mail.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kontact-news.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kontact-notes.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kontact-summary.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kontact-todo.png
  File ${prefix}/share/icons/oxygen/16x16/actions/konv-message.png
  File ${prefix}/share/icons/oxygen/16x16/actions/konv-message2.png
  File ${prefix}/share/icons/oxygen/16x16/actions/kscd-dock.png
  File ${prefix}/share/icons/oxygen/16x16/actions/laptop-charge-klaptopdaemon.png
  File ${prefix}/share/icons/oxygen/16x16/actions/laptop-nobattery-klaptopdaemon.png
  File ${prefix}/share/icons/oxygen/16x16/actions/laptop-nocharge-klaptopdaemon.png
  File ${prefix}/share/icons/oxygen/16x16/actions/launch.png
  File ${prefix}/share/icons/oxygen/16x16/actions/list-add-font.png
  File ${prefix}/share/icons/oxygen/16x16/actions/list-add-user.png
  File ${prefix}/share/icons/oxygen/16x16/actions/list-add.png
  File ${prefix}/share/icons/oxygen/16x16/actions/list-remove-user.png
  File ${prefix}/share/icons/oxygen/16x16/actions/list-remove.png
  File ${prefix}/share/icons/oxygen/16x16/actions/list.png
  File ${prefix}/share/icons/oxygen/16x16/actions/locationbar-erase.png
  File ${prefix}/share/icons/oxygen/16x16/actions/love.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-delete.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-find.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-flag-kmail.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-flag.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-forward.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-get.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-ham-kmail.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-ham.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-mark-important.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-mark-notjunk.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-mark-read.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-mark-unread.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-message-new.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-new.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-queue.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-receive.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-reply-all.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-reply-list.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-reply-sender.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-replylist.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail-send.png
  File ${prefix}/share/icons/oxygen/16x16/actions/mail.png
  File ${prefix}/share/icons/oxygen/16x16/actions/matrix.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-eject.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-equalizer.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-playback-pause.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-playback-start.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-playback-stop.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-playlist-clear.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-playlist-refresh.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-playlist.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-podcast.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-record.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-scripts.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-seek-backward.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-seek-forward.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-skip-backward.png
  File ${prefix}/share/icons/oxygen/16x16/actions/media-skip-forward.png
  File ${prefix}/share/icons/oxygen/16x16/actions/month.png
  File ${prefix}/share/icons/oxygen/16x16/actions/network.png
  File ${prefix}/share/icons/oxygen/16x16/actions/news-subscribe.png
  File ${prefix}/share/icons/oxygen/16x16/actions/news-unsubscribe.png
  File ${prefix}/share/icons/oxygen/16x16/actions/no.png
  File ${prefix}/share/icons/oxygen/16x16/actions/none.png
  File ${prefix}/share/icons/oxygen/16x16/actions/note.png
  File ${prefix}/share/icons/oxygen/16x16/actions/note2.png
  File ${prefix}/share/icons/oxygen/16x16/actions/object-edit.png
  File ${prefix}/share/icons/oxygen/16x16/actions/object-rotate-left.png
  File ${prefix}/share/icons/oxygen/16x16/actions/object-rotate-right.png
  File ${prefix}/share/icons/oxygen/16x16/actions/ok.png
  File ${prefix}/share/icons/oxygen/16x16/actions/openterm.png
  File ${prefix}/share/icons/oxygen/16x16/actions/paintbrush.png
  File ${prefix}/share/icons/oxygen/16x16/actions/paperbag.png
  File ${prefix}/share/icons/oxygen/16x16/actions/paperclipreal.png
  File ${prefix}/share/icons/oxygen/16x16/actions/pen.png
  File ${prefix}/share/icons/oxygen/16x16/actions/pencil.png
  File ${prefix}/share/icons/oxygen/16x16/actions/pencil2.png
  File ${prefix}/share/icons/oxygen/16x16/actions/player-time.png
  File ${prefix}/share/icons/oxygen/16x16/actions/player-volume.png
  File ${prefix}/share/icons/oxygen/16x16/actions/plus.png
  File ${prefix}/share/icons/oxygen/16x16/actions/print-frame.png
  File ${prefix}/share/icons/oxygen/16x16/actions/process-stop.png
  File ${prefix}/share/icons/oxygen/16x16/actions/project-open.png
  File ${prefix}/share/icons/oxygen/16x16/actions/rating.png
  File ${prefix}/share/icons/oxygen/16x16/actions/rebuild.png
  File ${prefix}/share/icons/oxygen/16x16/actions/roll.png
  File ${prefix}/share/icons/oxygen/16x16/actions/rotate.png
  File ${prefix}/share/icons/oxygen/16x16/actions/rss-tag.png
  File ${prefix}/share/icons/oxygen/16x16/actions/rss.png
  File ${prefix}/share/icons/oxygen/16x16/actions/ruler.png
  File ${prefix}/share/icons/oxygen/16x16/actions/run-build-file.png
  File ${prefix}/share/icons/oxygen/16x16/actions/run-build.png
  File ${prefix}/share/icons/oxygen/16x16/actions/save-all.png
  File ${prefix}/share/icons/oxygen/16x16/actions/screwdriver.png
  File ${prefix}/share/icons/oxygen/16x16/actions/search-filter.png
  File ${prefix}/share/icons/oxygen/16x16/actions/search-user.png
  File ${prefix}/share/icons/oxygen/16x16/actions/services.png
  File ${prefix}/share/icons/oxygen/16x16/actions/show-menu.png
  File ${prefix}/share/icons/oxygen/16x16/actions/show-offliners.png
  File ${prefix}/share/icons/oxygen/16x16/actions/signature.png
  File ${prefix}/share/icons/oxygen/16x16/actions/smiley.png
  File ${prefix}/share/icons/oxygen/16x16/actions/speaker.png
  File ${prefix}/share/icons/oxygen/16x16/actions/spread.png
  File ${prefix}/share/icons/oxygen/16x16/actions/stamp.png
  File ${prefix}/share/icons/oxygen/16x16/actions/switchuser.png
  File ${prefix}/share/icons/oxygen/16x16/actions/system-lock-screen.png
  File ${prefix}/share/icons/oxygen/16x16/actions/system-log-out.png
  File ${prefix}/share/icons/oxygen/16x16/actions/system-run.png
  File ${prefix}/share/icons/oxygen/16x16/actions/system-search.png
  File ${prefix}/share/icons/oxygen/16x16/actions/system-switch-user.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tab-breakoff.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tab-close.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tab-detach.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tab-duplicate.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tab-new-background.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tab-new-raised.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tab-new.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tab-remove.png
  File ${prefix}/share/icons/oxygen/16x16/actions/table.png
  File ${prefix}/share/icons/oxygen/16x16/actions/text-speak.png
  File ${prefix}/share/icons/oxygen/16x16/actions/text.png
  File ${prefix}/share/icons/oxygen/16x16/actions/thumbnail-show.png
  File ${prefix}/share/icons/oxygen/16x16/actions/todo.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tool.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tool2.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tools-check-spelling.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tools-media-optical-burn.png
  File ${prefix}/share/icons/oxygen/16x16/actions/tools-media-optical-copy.png
  File ${prefix}/share/icons/oxygen/16x16/actions/transform-rotate.png
  File ${prefix}/share/icons/oxygen/16x16/actions/trash-empty.png
  File ${prefix}/share/icons/oxygen/16x16/actions/underconstruction.png
  File ${prefix}/share/icons/oxygen/16x16/actions/user-female.png
  File ${prefix}/share/icons/oxygen/16x16/actions/user-group-new.png
  File ${prefix}/share/icons/oxygen/16x16/actions/user.png
  File ${prefix}/share/icons/oxygen/16x16/actions/users.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-day.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-list.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-month.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-tasks.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-time-spent.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-timeline.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-upcoming-days.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-upcoming-events.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-week.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-calendar-workweek.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-choose.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-close.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-filter.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-fullscreen.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-history.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-icon.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-left-right.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-media-artist.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-media-equalizer.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-media-lyrics.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-media-visualization.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-pim-calendar.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-pim-contacts.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-pim-journal.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-pim-mail.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-pim-news.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-pim-notes.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-pim-summary.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-pim-tasks.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-preview.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-process-all-tree.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-process-all.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-process-own.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-process-system.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-process-users.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-refresh.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-remove.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-restore.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-sidetree.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-statistics.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-top-bottom.png
  File ${prefix}/share/icons/oxygen/16x16/actions/view-tree.png
  File ${prefix}/share/icons/oxygen/16x16/actions/viewmag1.png
  File ${prefix}/share/icons/oxygen/16x16/actions/wallet-closed.png
  File ${prefix}/share/icons/oxygen/16x16/actions/wallet-open.png
  File ${prefix}/share/icons/oxygen/16x16/actions/whatsnext.png
  File ${prefix}/share/icons/oxygen/16x16/actions/window-close.png
  File ${prefix}/share/icons/oxygen/16x16/actions/window-new.png
  File ${prefix}/share/icons/oxygen/16x16/actions/window-suppressed.png
  File ${prefix}/share/icons/oxygen/16x16/actions/world.png
  File ${prefix}/share/icons/oxygen/16x16/actions/xdays.png
  File ${prefix}/share/icons/oxygen/16x16/actions/zoom-best-fit.png
  File ${prefix}/share/icons/oxygen/16x16/actions/zoom-in.png
  File ${prefix}/share/icons/oxygen/16x16/actions/zoom-original.png
  File ${prefix}/share/icons/oxygen/16x16/actions/zoom-out.png

  SetOutPath "$INSTDIR\share\icons\oxygen\16x16\apps"

  File ${prefix}/share/icons/oxygen/16x16/apps/KEduca.png
  File ${prefix}/share/icons/oxygen/16x16/apps/KLatin.png
  File ${prefix}/share/icons/oxygen/16x16/apps/KPercentage.png
  File ${prefix}/share/icons/oxygen/16x16/apps/KSniffer.png
  File ${prefix}/share/icons/oxygen/16x16/apps/KVerbos.png
  File ${prefix}/share/icons/oxygen/16x16/apps/KWordQuiz.png
  File ${prefix}/share/icons/oxygen/16x16/apps/KmPlot.png
  File ${prefix}/share/icons/oxygen/16x16/apps/abiword.png
  File ${prefix}/share/icons/oxygen/16x16/apps/accessories-calculator.png
  File ${prefix}/share/icons/oxygen/16x16/apps/accessories-character-map.png
  File ${prefix}/share/icons/oxygen/16x16/apps/accessories-dictionary.png
  File ${prefix}/share/icons/oxygen/16x16/apps/accessories-text-editor.png
  File ${prefix}/share/icons/oxygen/16x16/apps/acroread.png
  File ${prefix}/share/icons/oxygen/16x16/apps/akregator.png
  File ${prefix}/share/icons/oxygen/16x16/apps/alevt.png
  File ${prefix}/share/icons/oxygen/16x16/apps/applixware.png
  File ${prefix}/share/icons/oxygen/16x16/apps/assistant.png
  File ${prefix}/share/icons/oxygen/16x16/apps/basket.png
  File ${prefix}/share/icons/oxygen/16x16/apps/blender.png
  File ${prefix}/share/icons/oxygen/16x16/apps/bluefish.png
  File ${prefix}/share/icons/oxygen/16x16/apps/bovo.png
  File ${prefix}/share/icons/oxygen/16x16/apps/clanbomber.png
  File ${prefix}/share/icons/oxygen/16x16/apps/designer.png
  File ${prefix}/share/icons/oxygen/16x16/apps/dia.png
  File ${prefix}/share/icons/oxygen/16x16/apps/digikam.png
  File ${prefix}/share/icons/oxygen/16x16/apps/eclipse.png
  File ${prefix}/share/icons/oxygen/16x16/apps/emacs.png
  File ${prefix}/share/icons/oxygen/16x16/apps/email.png
  File ${prefix}/share/icons/oxygen/16x16/apps/evolution.png
  File ${prefix}/share/icons/oxygen/16x16/apps/fontforge.png
  File ${prefix}/share/icons/oxygen/16x16/apps/gabber.png
  File ${prefix}/share/icons/oxygen/16x16/apps/gaim.png
  File ${prefix}/share/icons/oxygen/16x16/apps/gimp.png
  File ${prefix}/share/icons/oxygen/16x16/apps/gnomemeeting.png
  File ${prefix}/share/icons/oxygen/16x16/apps/gnucash.png
  File ${prefix}/share/icons/oxygen/16x16/apps/gnumeric.png
  File ${prefix}/share/icons/oxygen/16x16/apps/graphics-viewer-document.png
  File ${prefix}/share/icons/oxygen/16x16/apps/gv.png
  File ${prefix}/share/icons/oxygen/16x16/apps/gvim.png
  File ${prefix}/share/icons/oxygen/16x16/apps/gwenview.png
  File ${prefix}/share/icons/oxygen/16x16/apps/help-browser.png
  File ${prefix}/share/icons/oxygen/16x16/apps/hwinfo.png
  File ${prefix}/share/icons/oxygen/16x16/apps/inkscape.png
  File ${prefix}/share/icons/oxygen/16x16/apps/internet-web-browser.png
  File ${prefix}/share/icons/oxygen/16x16/apps/java.png
  File ${prefix}/share/icons/oxygen/16x16/apps/k3b.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kaddressbook.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kaffeine.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kanagram.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kate.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kblogger.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kbruch.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kbugbuster.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kcall.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kchart.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kcolorchooser.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kde.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kexi.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kgeography.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kget.png
  File ${prefix}/share/icons/oxygen/16x16/apps/khangman.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kiten.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kjournal.png
  File ${prefix}/share/icons/oxygen/16x16/apps/klettres.png
  File ${prefix}/share/icons/oxygen/16x16/apps/klipper.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kmail.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kmplayer.png
  File ${prefix}/share/icons/oxygen/16x16/apps/knotes.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kolf.png
  File ${prefix}/share/icons/oxygen/16x16/apps/konqueror.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kontact.png
  File ${prefix}/share/icons/oxygen/16x16/apps/konversation.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kopete.png
  File ${prefix}/share/icons/oxygen/16x16/apps/krdc.png
  File ${prefix}/share/icons/oxygen/16x16/apps/krfb.png
  File ${prefix}/share/icons/oxygen/16x16/apps/krita.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kruler.png
  File ${prefix}/share/icons/oxygen/16x16/apps/ksim-cpu.png
  File ${prefix}/share/icons/oxygen/16x16/apps/ksnapshot.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kstars.png
  File ${prefix}/share/icons/oxygen/16x16/apps/ksudoku.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kteatime.png
  File ${prefix}/share/icons/oxygen/16x16/apps/ktorrent.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kuickshow.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kwallet.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kwalletmanager.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kword.png
  File ${prefix}/share/icons/oxygen/16x16/apps/kwrite.png
  File ${prefix}/share/icons/oxygen/16x16/apps/laptop-battery.png
  File ${prefix}/share/icons/oxygen/16x16/apps/licq.png
  File ${prefix}/share/icons/oxygen/16x16/apps/linguist.png
  File ${prefix}/share/icons/oxygen/16x16/apps/lyx.png
  File ${prefix}/share/icons/oxygen/16x16/apps/marble.png
  File ${prefix}/share/icons/oxygen/16x16/apps/multimedia-volume-control.png
  File ${prefix}/share/icons/oxygen/16x16/apps/netscape.png
  File ${prefix}/share/icons/oxygen/16x16/apps/none.png
  File ${prefix}/share/icons/oxygen/16x16/apps/office-addressbook.png
  File ${prefix}/share/icons/oxygen/16x16/apps/office-calendar.png
  File ${prefix}/share/icons/oxygen/16x16/apps/opera.png
  File ${prefix}/share/icons/oxygen/16x16/apps/pan.png
  File ${prefix}/share/icons/oxygen/16x16/apps/penguin.png
  File ${prefix}/share/icons/oxygen/16x16/apps/plan.png
  File ${prefix}/share/icons/oxygen/16x16/apps/planner.png
  File ${prefix}/share/icons/oxygen/16x16/apps/plasmagik.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-contact-list.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-accessibility.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-color.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-cryptography.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-default-applications.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-display.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-filetype-association.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-font.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-gaming.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-icons.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-keyboard.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-launch-feedback.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-locale.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-mouse.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-notification-bell.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-notification.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-printer.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-screensaver.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-sound.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-text-to-speech.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-theme.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-user-password.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-user.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-desktop-wallpaper.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-kcalc-constants.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-other.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-system-bluetooth.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-system-login.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-system-network-sharing.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-system-performance.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-system-power-management.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-system-session-services.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-system-time.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-system-windows.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-web-browser-adblock.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-web-browser-cache.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-web-browser-cookies.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-web-browser-identification.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-web-browser-shortcuts.png
  File ${prefix}/share/icons/oxygen/16x16/apps/preferences-web-browser-stylesheets.png
  File ${prefix}/share/icons/oxygen/16x16/apps/pybliographic.png
  File ${prefix}/share/icons/oxygen/16x16/apps/realplayer.png
  File ${prefix}/share/icons/oxygen/16x16/apps/scribus.png
  File ${prefix}/share/icons/oxygen/16x16/apps/sodipodi.png
  File ${prefix}/share/icons/oxygen/16x16/apps/strigi.png
  File ${prefix}/share/icons/oxygen/16x16/apps/system-file-manager.png
  File ${prefix}/share/icons/oxygen/16x16/apps/system-software-update.png
  File ${prefix}/share/icons/oxygen/16x16/apps/system-users.png
  File ${prefix}/share/icons/oxygen/16x16/apps/tagua.png
  File ${prefix}/share/icons/oxygen/16x16/apps/terminal.png
  File ${prefix}/share/icons/oxygen/16x16/apps/tux.png
  File ${prefix}/share/icons/oxygen/16x16/apps/utilities-file-archiver.png
  File ${prefix}/share/icons/oxygen/16x16/apps/utilities-log-viewer.png
  File ${prefix}/share/icons/oxygen/16x16/apps/utilities-system-monitor.png
  File ${prefix}/share/icons/oxygen/16x16/apps/utilities-terminal.png
  File ${prefix}/share/icons/oxygen/16x16/apps/wine.png
  File ${prefix}/share/icons/oxygen/16x16/apps/wp.png
  File ${prefix}/share/icons/oxygen/16x16/apps/x.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xcalc.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xchat.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xclipboard.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xclock.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xedit.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xemacs.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xeyes.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xfig.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xfmail.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xload.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xmag.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xmms.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xosview.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xpaint.png
  File ${prefix}/share/icons/oxygen/16x16/apps/xv.png

  SetOutPath "$INSTDIR\share\icons\oxygen\16x16\categories"

  File ${prefix}/share/icons/oxygen/16x16/categories/applications-accessories.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-development.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-education.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-engineering.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-games.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-graphics.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-internet.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-multimedia.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-office.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-other.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-science.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-system.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-toys.png
  File ${prefix}/share/icons/oxygen/16x16/categories/applications-utilities.png
  File ${prefix}/share/icons/oxygen/16x16/categories/preferences-desktop-peripherals.png
  File ${prefix}/share/icons/oxygen/16x16/categories/preferences-desktop-personal.png
  File ${prefix}/share/icons/oxygen/16x16/categories/preferences-desktop.png
  File ${prefix}/share/icons/oxygen/16x16/categories/preferences-system-network.png
  File ${prefix}/share/icons/oxygen/16x16/categories/preferences-system.png
  File ${prefix}/share/icons/oxygen/16x16/categories/system-help.png

  SetOutPath "$INSTDIR\share\icons\oxygen\16x16\devices"

  File ${prefix}/share/icons/oxygen/16x16/devices/audio-card.png
  File ${prefix}/share/icons/oxygen/16x16/devices/audio-headset.png
  File ${prefix}/share/icons/oxygen/16x16/devices/audio-input-line.png
  File ${prefix}/share/icons/oxygen/16x16/devices/audio-input-microphone.png
  File ${prefix}/share/icons/oxygen/16x16/devices/battery.png
  File ${prefix}/share/icons/oxygen/16x16/devices/camera-photo.png
  File ${prefix}/share/icons/oxygen/16x16/devices/camera-web.png
  File ${prefix}/share/icons/oxygen/16x16/devices/computer-laptop.png
  File ${prefix}/share/icons/oxygen/16x16/devices/computer.png
  File ${prefix}/share/icons/oxygen/16x16/devices/cpu.png
  File ${prefix}/share/icons/oxygen/16x16/devices/drive-harddisk.png
  File ${prefix}/share/icons/oxygen/16x16/devices/drive-optical.png
  File ${prefix}/share/icons/oxygen/16x16/devices/drive-remote.png
  File ${prefix}/share/icons/oxygen/16x16/devices/drive-removable-media-usb-pendrive.png
  File ${prefix}/share/icons/oxygen/16x16/devices/drive-removable-media-usb.png
  File ${prefix}/share/icons/oxygen/16x16/devices/drive-removable-media.png
  File ${prefix}/share/icons/oxygen/16x16/devices/input-gaming.png
  File ${prefix}/share/icons/oxygen/16x16/devices/input-keyboard.png
  File ${prefix}/share/icons/oxygen/16x16/devices/input-mouse.png
  File ${prefix}/share/icons/oxygen/16x16/devices/input-tablet.png
  File ${prefix}/share/icons/oxygen/16x16/devices/media-flash-memory-stick.png
  File ${prefix}/share/icons/oxygen/16x16/devices/media-flash-sd-mmc.png
  File ${prefix}/share/icons/oxygen/16x16/devices/media-flash-smart-media.png
  File ${prefix}/share/icons/oxygen/16x16/devices/media-flash.png
  File ${prefix}/share/icons/oxygen/16x16/devices/media-floppy.png
  File ${prefix}/share/icons/oxygen/16x16/devices/media-optical-audio.png
  File ${prefix}/share/icons/oxygen/16x16/devices/media-optical-recordable.png
  File ${prefix}/share/icons/oxygen/16x16/devices/media-optical.png
  File ${prefix}/share/icons/oxygen/16x16/devices/media-tape.png
  File ${prefix}/share/icons/oxygen/16x16/devices/modem.png
  File ${prefix}/share/icons/oxygen/16x16/devices/multimedia-player-apple-ipod.png
  File ${prefix}/share/icons/oxygen/16x16/devices/multimedia-player.png
  File ${prefix}/share/icons/oxygen/16x16/devices/network-wired.png
  File ${prefix}/share/icons/oxygen/16x16/devices/network-wireless.png
  File ${prefix}/share/icons/oxygen/16x16/devices/pda.png
  File ${prefix}/share/icons/oxygen/16x16/devices/phone.png
  File ${prefix}/share/icons/oxygen/16x16/devices/printer.png
  File ${prefix}/share/icons/oxygen/16x16/devices/scanner.png
  File ${prefix}/share/icons/oxygen/16x16/devices/video-display.png
  File ${prefix}/share/icons/oxygen/16x16/devices/video-projector.png
  File ${prefix}/share/icons/oxygen/16x16/devices/video-television.png

  SetOutPath "$INSTDIR\share\icons\oxygen\16x16\emblems"

  File ${prefix}/share/icons/oxygen/16x16/emblems/emblem-favorite.png
  File ${prefix}/share/icons/oxygen/16x16/emblems/emblem-mounted.png
  File ${prefix}/share/icons/oxygen/16x16/emblems/emblem-symbolic-link.png

  SetOutPath "$INSTDIR\share\icons\oxygen\16x16\mimetypes"

  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-illustrator.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-octet-stream.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-pdf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-pgp-encrypted.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-pgp-signature.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-pgp.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-pkcs7-mime.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-relaxng.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-rss+xml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-rtf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.ms-excel.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.ms-powerpoint.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.ms-word.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.chart.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.database.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.formula.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.graphics.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.image.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.presentation-template.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.presentation.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.spreadsheet-template.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.spreadsheet.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.oasis.opendocument.text.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.rn-realmedia.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.stardivision.calc.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.stardivision.draw.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.sun.xml.calc.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.sun.xml.calc.template.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.sun.xml.draw.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-vnd.sun.xml.draw.template.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-7z-compressed.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-ace.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-applix-spreadsheet.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-ar.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-arc.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-archive.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-arj.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-awk.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-bittorrent.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-bzdvi.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-bzip-compressed-tar.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-bzip.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-cd-image.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-cda.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-compress.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-compressed-tar.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-cpio.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-cue.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-deb.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-designer.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-desktop.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-egon.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-executable-script.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-executable.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-font-afm.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-font-bdf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-font-otf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-font-pcf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-font-snf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-font-ttf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-font-type1.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-gnumeric.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-gzdvi.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-gzip.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-gzpostscript.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-java-applet.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-java-archive.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-java.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-kcsrc.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-kgetlist.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-kontour.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-krita.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-lha.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-lzop.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-marble.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-mimearchive.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-mplayer2.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-ms-dos-executable.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-mswinurl.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-mswrite.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-nzb.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-object.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-pak.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-perl.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-php.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-plasma.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-python-bytecode.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-quattropro.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-rar.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-rpm.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-ruby.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-sharedlib.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-shellscript.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-siag.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-tar.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-tarz.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-tgif.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-trash.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-troff-man.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-tzo.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-wmf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-zerosize.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-x-zoo.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-xhtml+xml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-xml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-xsd.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-xslt+xml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/application-zip.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/ascii.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-aac.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-ac3.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-basic.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-midi.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-mp4.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-mpeg.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-prs.sid.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-vnd.rn-realaudio.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-vnd.rn-realvideo.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-adpcm.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-aiff.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-flac+ogg.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-flac.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-generic.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-matroska.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-mod.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-monkey.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-mp2.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-mpegurl.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-ms-wma.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-musepack.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-pn-realaudio-plugin.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-scpls.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-speex+ogg.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-vorbis+ogg.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/audio-x-wav.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/binary.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/cdbo-list.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/cdimage.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/cdtrack.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/document.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/empty.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/encrypted.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/font-bitmap.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/font-truetype.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/font-type1.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/html.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-bmp.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-cgm.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-fax-g3.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-gif.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-jpeg.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-jpeg2000.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-png.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-svg+xml-compressed.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-svg+xml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-tiff.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-applix-graphics.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-dcraw.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-dds.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-eps.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-exr.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-fits.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-generic.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-hdr.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-ico.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-jng.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-msod.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-pcx.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-photo-cd.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-portable-bitmap.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-portable-graymap.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-portable-pixmap.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-psd.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-rgb.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-tga.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-vnd.trolltech.qpicture.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-xbitmap.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-xcf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-xfig.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image-x-xpixmap.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/image.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/info.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/inode-directory.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/kwordquiz-do.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/make.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/man.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/message-news.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/message-rfc822.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/message.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/news.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/none.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/odf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/pdf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/recycled.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/shellscript.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/sound.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/spreadsheet.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/tar.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/tex.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-calendar.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-css.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-csv.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-directory.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-enriched.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-html.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-mathml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-plain.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-rdf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-rtf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-sgml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-troff.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-vcalendar.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-vnd.abc.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-vnd.wap.wml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-adasrc.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-bibtex.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-c++hdr.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-c++src.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-chdr.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-csharp.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-csrc.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-dtd.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-generic.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-hex.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-java.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-katefilelist.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-ldif.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-makefile.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-objchdr.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-objcsrc.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-pascal.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-patch.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-python.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-script.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-tcl.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-tex.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-texinfo.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-vcard.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-x-xslfo.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-xmcd.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/text-xml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/tgz.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/txt.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/unknown.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/uri-mms.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/uri-mmst.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/uri-mmsu.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/uri-pnm.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/uri-rtspt.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/uri-rtspu.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/vcalendar.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/vcard.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/vectorgfx.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-mp4.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-mpeg.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-quicktime.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-x-flic.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-x-generic.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-x-matroska.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-x-mng.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-x-ms-asf.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-x-ms-wmv.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-x-msvideo.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-x-ogm+ogg.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video-x-theora+ogg.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/video.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/x-office-document.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/x-office-spreadsheet.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/xml.png
  File ${prefix}/share/icons/oxygen/16x16/mimetypes/zip.png

  SetOutPath "$INSTDIR\share\icons\oxygen\16x16\places"

  File ${prefix}/share/icons/oxygen/16x16/places/bookmark.png
  File ${prefix}/share/icons/oxygen/16x16/places/contact.png
  File ${prefix}/share/icons/oxygen/16x16/places/document-multiple.png
  File ${prefix}/share/icons/oxygen/16x16/places/file-broken.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-blue.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-bookmarks.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-brown.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-cyan.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-development.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-downloads.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-green.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-grey.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-html.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-image.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-important.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-locked.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-orange.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-print.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-red.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-sound.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-tar.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-txt.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-video.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-violet.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder-yellow.png
  File ${prefix}/share/icons/oxygen/16x16/places/folder.png
  File ${prefix}/share/icons/oxygen/16x16/places/mail-inbox.png
  File ${prefix}/share/icons/oxygen/16x16/places/mail-message.png
  File ${prefix}/share/icons/oxygen/16x16/places/mail-outbox.png
  File ${prefix}/share/icons/oxygen/16x16/places/mail.png
  File ${prefix}/share/icons/oxygen/16x16/places/media-album.png
  File ${prefix}/share/icons/oxygen/16x16/places/media-playlist.png
  File ${prefix}/share/icons/oxygen/16x16/places/media-podcast.png
  File ${prefix}/share/icons/oxygen/16x16/places/network-local.png
  File ${prefix}/share/icons/oxygen/16x16/places/network-server-database.png
  File ${prefix}/share/icons/oxygen/16x16/places/network-server.png
  File ${prefix}/share/icons/oxygen/16x16/places/network-wired.png
  File ${prefix}/share/icons/oxygen/16x16/places/network-workgroup.png
  File ${prefix}/share/icons/oxygen/16x16/places/network.png
  File ${prefix}/share/icons/oxygen/16x16/places/start-here.png
  File ${prefix}/share/icons/oxygen/16x16/places/trashcan-empty-alt.png
  File ${prefix}/share/icons/oxygen/16x16/places/user-desktop.png
  File ${prefix}/share/icons/oxygen/16x16/places/user-home.png
  File ${prefix}/share/icons/oxygen/16x16/places/user-trash.png

  SetOutPath "$INSTDIR\share\icons\oxygen\16x16\status"

  File ${prefix}/share/icons/oxygen/16x16/status/battery-040.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-060.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-080.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-100.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-caution.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-charging-040.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-charging-060.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-charging-080.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-charging-caution.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-charging-low.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-charging.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-low.png
  File ${prefix}/share/icons/oxygen/16x16/status/battery-missing.png
  File ${prefix}/share/icons/oxygen/16x16/status/dialog-error.png
  File ${prefix}/share/icons/oxygen/16x16/status/dialog-information.png
  File ${prefix}/share/icons/oxygen/16x16/status/dialog-password.png
  File ${prefix}/share/icons/oxygen/16x16/status/dialog-warning.png
  File ${prefix}/share/icons/oxygen/16x16/status/folder-open.png
  File ${prefix}/share/icons/oxygen/16x16/status/image-loading.png
  File ${prefix}/share/icons/oxygen/16x16/status/image-missing.png
  File ${prefix}/share/icons/oxygen/16x16/status/mail-attachment.png
  File ${prefix}/share/icons/oxygen/16x16/status/mail-read.png
  File ${prefix}/share/icons/oxygen/16x16/status/mail-unread.png
  File ${prefix}/share/icons/oxygen/16x16/status/media-playlist-shuffle.png
  File ${prefix}/share/icons/oxygen/16x16/status/object-locked.png
  File ${prefix}/share/icons/oxygen/16x16/status/object-unlocked.png
  File ${prefix}/share/icons/oxygen/16x16/status/printer-error.png
  File ${prefix}/share/icons/oxygen/16x16/status/printer-printing.png
  File ${prefix}/share/icons/oxygen/16x16/status/security-high.png
  File ${prefix}/share/icons/oxygen/16x16/status/security-low.png
  File ${prefix}/share/icons/oxygen/16x16/status/security-medium.png
  File ${prefix}/share/icons/oxygen/16x16/status/user-away-extended.png
  File ${prefix}/share/icons/oxygen/16x16/status/user-away.png
  File ${prefix}/share/icons/oxygen/16x16/status/user-busy.png
  File ${prefix}/share/icons/oxygen/16x16/status/user-offline.png
  File ${prefix}/share/icons/oxygen/16x16/status/user-online.png
  File ${prefix}/share/icons/oxygen/16x16/status/user-trash-full.png
  File ${prefix}/share/icons/oxygen/16x16/status/wallet-closed.png
  File ${prefix}/share/icons/oxygen/16x16/status/wallet-open.png

  SetOutPath "$INSTDIR\share\icons\oxygen"

  File ${prefix}/share/icons/oxygen/index.theme

!endif
SectionEnd
