#!/bin/bash
# Copyright (C) 2023 g10 Code GmbH
#
# Software engineering by Andre Heinecke <aheinecke@gnupg.org>
#
# This file is part of GPG4Win.
#
# GPG4Win is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# GPG4Win is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-2.0+

# This is just a list of all the breeze icon names.
# find /usr/share/icons/breeze -name \*.svg | \
#  sed  's@/usr/share/icons/breeze/.*/@@' | sed 's@.svg@@' | \
#  sort -u > allicons.txt

# The scriptlet then grepps the source code of the repo for them
# and looks if they are part of the inst-breeze-icons.nsi file already.
# If not then it will list them and I add them manually.

set -e

if [ -z "$1" ]; then
    echo "Usage $0 <sourcedir_to_grep_trough>"
    exit 1
fi

ICONS="
accept_signal
accept_time_event
accessories-calculator
accessories-character-map
accessories-dictionary-symbolic
accessories-text-editor
acrobat
acroread
action-albumfolder-importdir2
action-rss_tag
action-unavailable-symbolic
activities
activity-fork
actor
add-placemark
addressbook-details
address-book-new
address-book-new-symbolic
add-subtitle
adjustcol
adjustcurves
adjusthsl
adjustlevels
adjustrgb
adjustrow
adress-book-new
aggregation
akonadiconsole
akonadi-phone-home
akregator
alarm-symbolic
albumfolder-importdir
albumfolder-importimages
albumfolder-new
albumfolder-properties
albumfolder-user-trash
alienarena
align-horizontal-baseline
align-horizontal-bottom-out
align-horizontal-center
align-horizontal-left
align-horizontal-left-out
align-horizontal-left-to-anchor
align-horizontal-node
align-horizontal-right
align-horizontal-right-out
align-horizontal-right-to-anchor
align-horizontal-top-out
align-vertical-baseline
align-vertical-bottom
align-vertical-bottom-out
align-vertical-bottom-to-anchor
align-vertical-center
align-vertical-node
align-vertical-top
align-vertical-top-out
align-vertical-top-to-anchor
alligator
amarok
amarok_artist
amarok_cart_add
amarok_cart_remove
amarok_cart_view
amarok_change_language
amarok_clock
amarok_lyrics
amarok_playcount
amarok_playlist
amarok_playlist_refresh
amarok_scripts
anchor
android-file-transfer
android-package-archive
android-studio
animal
animation-stage
anjuta
answer
answer-correct
antivignetting
anydesk
apper
applets-template
application-atom+xml
application-certificate
application-dicom
application-epub+zip
application-exit
application-exit-symbolic
application-gzip
application-illustrator
application-javascript
application-json
application-mac-binhex40
application-mathml+xml
application-menu
application-msonenote
application-msoutlook
application-msword
application-msword-template
application-octet-stream
application-ogg
application-pdf
application-pgp
application-pgp-encrypted
application-pgp-keys
application-pgp-signature
application-pkcs12
application-pkcs7-mime
application-pkcs7-signature
application-pkix-cerl
application-pkix-cert
application-postscript
application-relaxng
application-rss+xml
application-rtf
applications-all
applications-development
applications-education
applications-education-language
applications-education-mathematics
applications-education-science
applications-engineering
applications-games
applications-graphics
applications-internet
applications-multimedia
applications-network
applications-office
applications-other
application-sql
applications-science
applications-system
applications-utilities
application-sxw
application-vnd.android.package-archive
application-vnd.appimage
application-vnd.apple.pkpass
application-vnd.debian.binary-package
application-vnd.flatpak.ref
application-vnd.google-earth.kml+xml
application-vnd.iccprofile
application-vnd.kde.kleopatra.keygroup
application-vnd.ms-access
application-vnd.ms-excel
application-vnd.ms-excel.addin.macroenabled.12
application-vnd.ms-excel.sheet.binary.macroenabled.12
application-vnd.ms-excel.sheet.macroenabled.12
application-vnd.ms-excel.template.macroenabled.12
application-vnd.ms-infopath
application-vnd.ms-powerpoint
application-vnd.ms-powerpoint.addin.macroenabled.12
application-vnd.ms-powerpoint.presentation.macroenabled.12
application-vnd.ms-powerpoint.slide.macroenabled.12
application-vnd.ms-powerpoint.slideshow.macroenabled.12
application-vnd.ms-powerpoint.template.macroenabled.12
application-vnd.ms-publisher
application-vnd.ms-word
application-vnd.ms-word.document.macroenabled.12
application-vnd.ms-word.template.macroenabled.12
application-vnd.nintendo.snes.rom
application-vnd.nokia.xml.qt.resource
application-vnd.oasis.opendocument.chart
application-vnd.oasis.opendocument.database
application-vnd.oasis.opendocument.drawing
application-vnd.oasis.opendocument.drawing.template
application-vnd.oasis.opendocument.draw.template
application-vnd.oasis.opendocument.formula
application-vnd.oasis.opendocument.formula-template
application-vnd.oasis.opendocument.graphics
application-vnd.oasis.opendocument.image
application-vnd.oasis.opendocument.presentation
application-vnd.oasis.opendocument.presentation-template
application-vnd.oasis.opendocument.spreadsheet
application-vnd.oasis.opendocument.spreadsheet-template
application-vnd.oasis.opendocument.text
application-vnd.oasis.opendocument.text-master
application-vnd.oasis.opendocument.text-template
application-vnd.oasis.opendocument.web-template
application-vnd.openofficeorg.extension
application-vnd.openxmlformats-officedocument.spreadsheetml.sheet
application-vnd.openxmlformats-officedocument.wordprocessingml.document
application-vnd.rar
application-vnd.rn-realmedia
application-vnd.scribus
application-vnd.sqlite3
application-vnd.squashfs
application-vnd.stardivision.calc
application-vnd.stardivision.draw
application-vnd.stardivision.mail
application-vnd.stardivision.math
application-vnd.sun.xml.calc
application-vnd.sun.xml.calc.template
application-vnd.sun.xml.draw
application-vnd.sun.xml.draw.template
application-vnd.sun.xml.impress
application-vnd.sun.xml.impress.template
application-vnd.sun.xml.math
application-vnd.sun.xml.writer
application-vnd.sun.xml.writer.global
application-vnd.sun.xml.writer.template
application-vnd.visio
application-vnd.wordperfect
application-wps-office.doc
application-wps-office.docx
application-wps-office.dot
application-wps-office.dotx
application-wps-office.pot
application-wps-office.potx
application-wps-office.ppt
application-wps-office.pptx
application-wps-office.xls
application-wps-office.xlsx
application-wps-office.xlt
application-wps-office.xltx
application-x-7z-compressed
application-x-abiword
application-x-ace
application-x-apple-diskimage
application-x-applix-spreadsheet
application-x-applix-word
application-x-ar
application-x-arc
application-x-archive
application-x-arj
application-x-audacity-project
application-x-awk
application-x-bittorrent
application-x-blender
application-x-bzdvi
application-x-bzip
application-x-bzip-compressed-tar
application-x-cda
application-x-cd-image
application-x-chm
application-x-clementine
application-x-compress
application-x-compressed-tar
application-x-core
application-x-cpio
application-x-cue
application-x-deb
application-x-designer
application-x-desktop
application-x-egon
application-x-executable
application-x-executable-script
application-x-fictionbook+xml
application-x-flash-video
application-x-font-afm
application-x-font-bdf
application-x-font-otf
application-x-font-pcf
application-x-font-snf
application-x-font-ttf
application-x-font-ttx
application-x-font-type1
application-x-gameboy-rom
application-x-gamecube-rom
application-x-gba-rom
application-x-gdscript
application-x-gettext-translation
application-x-gnumeric
application-x-godot-project
application-x-godot-resource
application-x-godot-scene
application-x-godot-shader
application-x-gzdvi
application-x-gzip
application-x-gzpostscript
application-xhtml+xml
application-x-iso
application-x-iso9660-appimage
application-x-it87
application-x-jar
application-x-java
application-x-java-applet
application-x-java-archive
application-x-javascript
application-x-k3b
application-x-kcsrc
application-x-kdenlivetitle
application-x-kexi-connectiondata
application-x-kexiproject-shortcut
application-x-kexiproject-sqlite
application-x-kexiproject-sqlite2
application-x-kexiproject-sqlite3
application-x-kformula
application-x-kgetlist
application-x-kmymoney
application-x-kontour
application-x-kplato
application-x-krita
application-x-kvtml
application-x-kword
application-x-labplot2
application-x-lha
application-x-lyx
application-x-lzma-compressed-tar
application-x-lzop
application-x-m4
application-x-macbinary
application-x-marble
application-x-mimearchive
application-xmind
application-xml
application-x-mplayer2
application-x-ms-dos-executable
application-x-msdownload
application-x-ms-shortcut
application-x-ms-wim
application-x-mswinurl
application-x-mswrite
application-x-n64-rom
application-x-nes-rom
application-x-nintendo-ds-rom
application-x-nzb
application-x-object
application-x-pak
application-x-partial-download
application-x-pem-key
application-x-perl
application-x-php
application-x-pkcs12
application-x-pkcs7-certificates
application-x-plasma
application-x-python-bytecode
application-x-qemu-disk
application-x-qet-element
application-x-qet-project
application-x-quattropro
application-x-rar
application-x-raw-disk-image
application-x-rdata
application-x-root
application-x-rpm
application-x-ruby
application-x-sami
application-xsd
application-x-sharedlib
application-x-shellscript
application-x-shockwave-flash
application-x-siag
application-x-sif
application-x-skg
application-x-skgc
application-xslt+xml
application-x-smb-server
application-x-smb-workgroup
application-x-source-rpm
application-x-sqlite2
application-x-sqlite3
application-x-srt
application-x-srtrip
application-x-subrip
application-x-tar
application-x-tarz
application-x-tgif
application-x-theme
application-x-trash
application-x-troff-man
application-x-tzo
application-x-vdi-disk
application-x-wmf
application-x-x509-ca-cert
application-x-x509-user-cert
application-x-xliff
application-x-xpinstall
application-x-xz-compressed-tar
application-x-xz-pkg
application-x-zerosize
application-x-zip-compressed-fb2
application-x-zoo
application-zip
appointment-missed-symbolic
appointment-new
appointment-new-symbolic
appointment-recurring
appointment-reminder
appointment-soon-symbolic
approved
aptana
archive-extract
archive-insert
archive-insert-directory
archive-remove
ardour
ark
arrow
arrow-down
arrow-down-double
arrow-left
arrow-left-double
arrow-right
arrow-right-double
arrow-up
arrow-up-double
artifact
artikulate
artistictext-tool
assistant
association
atmosphere
atom
audacity
audio-ac3
audiobook
audio-card
audio-flac
audio-headphones
audio-headset
audio-input-microphone
audio-input-microphone-symbolic
audio-midi
audio-mp2
audio-mp3
audio-mp4
audio-mpeg
audio-off
audio-on
audio-prs.sid
audio-radio
audio-radio-symbolic
audio-ready
audio-speakers-symbolic
audio-vnd.rn-realvideo
audio-vn.rn-realmedia
audio-volume-high
audio-volume-high-symbolic
audio-volume-low
audio-volume-low-symbolic
audio-volume-medium
audio-volume-medium-symbolic
audio-volume-muted
audio-volume-muted-symbolic
audio-x-adpcm
audio-x-aiff
audio-x-flac
audio-x-flac+ogg
audio-x-generic
audio-x-monkey
audio-x-mp2
audio-x-mpeg
audio-x-speex+ogg
audio-x-wav
author
auth-sim
auth-sim-locked
auth-sim-locked-symbolic
auth-sim-missing
auth-sim-missing-symbolic
auth-sim-symbolic
autocorrection
automated-tasks
auto-scale-all
auto-scale-x
auto-scale-y
auto-transition
auto-type
avatar-default-symbolic
babe
backgroundtool
backup
baloo
battery
battery-000
battery-000-charging
battery-010
battery-010-charging
battery-020
battery-020-charging
battery-030
battery-030-charging
battery-040
battery-040-charging
battery-050
battery-050-charging
battery-060
battery-060-charging
battery-070
battery-070-charging
battery-080
battery-080-charging
battery-090
battery-090-charging
battery-100
battery-100-charging
battery-caution
battery-caution-charging
battery-caution-charging-symbolic
battery-caution-symbolic
battery-empty
battery-empty-charging
battery-empty-charging-symbolic
battery-empty-symbolic
battery-full
battery-full-charged-symbolic
battery-full-charging
battery-full-charging-symbolic
battery-full-symbolic
battery-good
battery-good-charging
battery-good-charging-symbolic
battery-good-symbolic
battery-low
battery-low-charging
battery-low-charging-symbolic
battery-low-symbolic
battery-missing
battery-missing-symbolic
battery-ups
bboxnext
bboxprev
beamerblock
beamerframe
bibtex
bigskip
bitcoin128
bitmap-trace
bittorrent-sync
black_sum
bleachbit
blender
blinken
blogilo
bluefish
bluegriffon
blurfx
blurimage
bomber
bomi
bookmark-add-folder
bookmark-add-symbolic
bookmark-edit
bookmark-new
bookmark-new-list
bookmark-new-symbolic
bookmark-remove
bookmarks
bookmarks-organize
bookmark-toolbar
borderpainter
bordertool
bovo
box
bqm-add
bqm-addqueue
bqm-commit
bqm-diff
bqm-remove
bqm-rmqueue
bqm-update
brackets
braindump
branch
breeze-settings
brightness-high
brightness-low
btsync-gui
buho
builder-view-left-pane-symbolic
bwtonal
calamares
calibre-ebook-edit
calibre-viewer
calindori
call-end-symbolic
calligraauthor
calligraflow
calligrakarbon
calligrakexi
calligraphy
calligraplan
calligraplanwork
calligrasheets
calligrastage
calligrawords
call-incoming
call-incoming-symbolic
call-missed
call-missed-symbolic
call-outgoing
call-outgoing-symbolic
callout-shape
call-start
call-start-symbolic
call-stop
call-stop-symbolic
call-voicemail
call-voicemail-symbolic
camera-off
camera-on
camera-photo
camera-photo-symbolic
camera-ready
camera-video
camera-video-symbolic
camera-web
camera-web-symbolic
cantata
cantor
car
cards-block
category
category2parent
cell_edit
cell_layout
certificate-server
cervisia
change-date-symbolic
changes-allow-symbolic
changes-prevent-symbolic
channel-insecure-symbolic
channelmixer
channel-secure-symbolic
character-set
charcoaltool
checkbox
checkbox-checked-symbolic
check_constraint
checkmark
child2category
choice-rhomb
choice-round
choqok
chronometer
chronometer-lap
chronometer-pause
chronometer-reset
chronometer-start
circular-arrow-shape
class
class-or-package
claws-mail
clementine
clock
clock-large
cloud-download
cloudstatus
cloud-upload
cmake
CMakeSetup
code-block
codeblocks
code-class
code-context
code-function
code-typedef
code-variable
collapse
collapse-all
collapse-all-symbolic
collection-rescan-amarok
color-fill
colorfx
color-gradient
color-management
colormanagement
color-mode-black-white
color-mode-hue-shift-negative
color-mode-hue-shift-positive
color-mode-invert-image
color-mode-invert-text
colorneg
color-picker
color-picker-black
color-picker-grey
color-picker-white
color-profile
colors-chromablue
colors-chromagreen
colors-chromared
color-select-symbolic
colors-luma
combined_fragment
com.github.ztefn.haguichi
com.github.ztefn.haguichi-connected
com.github.ztefn.haguichi-connecting-1
com.github.ztefn.haguichi-connecting-2
com.github.ztefn.haguichi-connecting-3
com.github.ztefn.haguichi-disconnected
comment-symbolic
compass
component
composite-track-off
composite-track-on
composite-track-preview
composition
computer
computer-fail-symbolic
computer-laptop
computer-symbolic
com.visualstudio.code
com.visualstudio.code.oss
configure
configure_kile
configure_project
configure-shortcuts
configure-toolbars
contact-new
contact-new-symbolic
containment
content-loading-symbolic
contents
contrast
converseen
convert
coordinate
copy-coordinates
cpu
createpath
crosshairs
cross-shape
crow-translate
crow-translate-tray
cups
cupsprinter
cursor-arrow
cursor-cross
curve-connector
cuttlefish
CVnamespace
darktable
dashboard-show
database-change-key
database-index
data-error
data-information
data-success
datatype
data-warning
dblatex
debug-execute-from-cursor
debug-execute-to-cursor
debug-run
debug-run-cursor
debug-step-instruction
debug-step-into
debug-step-into-instruction
debug-step-out
debug-step-over
deep-history
delete
deletecell
delete-comment
delete_table
delete-table-row
dependency
depth16to8
depth8to16
description
desktop
device-notifier
dfrac
diag_activity
diag_class
diag_component
dialog-align-and-distribute
dialog-cancel
dialog-close
dialog-error
dialog-error-symbolic
dialog-fill-and-stroke
dialog-filters
dialog-icon-preview
dialog-information
dialog-input-devices
dialog-layers
dialog-memory
dialog-messages
dialog-object-properties
dialog-ok
dialog-ok-apply
dialog-password
dialog-positive
dialog-question
dialog-rows-and-columns
dialog-scripts
dialog-text-and-font
dialog-tile-clones
dialog-transform
dialog-warning
dialog-warning-symbolic
dialog-xml-editor
diaspora
diffuse
digikam
dirsync
discrete
disk-quota
disk-quota-critical
disk-quota-high
disk-quota-low
displaymathmode
dissociatecell
distortionfx
distribute-graph
distribute-graph-directed
distribute-horizontal
distribute-horizontal-baseline
distribute-horizontal-center
distribute-horizontal-equal
distribute-horizontal-gaps
distribute-horizontal-left
distribute-horizontal-margin
distribute-horizontal-node
distribute-horizontal-page
distribute-horizontal-right
distribute-horizontal-x
distribute-randomize
distribute-remove-overlaps
distribute-unclump
distribute-vertical
distribute-vertical-baseline
distribute-vertical-bottom
distribute-vertical-center
distribute-vertical-equal
distribute-vertical-gaps
distribute-vertical-margin
distribute-vertical-node
distribute-vertical-page
distribute-vertical-top
distribute-vertical-y
documentation
document-cleanup
document-close
document-compareleft
document-compareright
document-decrypt
document-duplicate
document-edit
document-edit-decrypt
document-edit-decrypt-verify
document-edit-encrypt
document-edit-sign
document-edit-sign-encrypt
document-edit-symbolic
document-edit-verify
document-encrypt
document-encrypted
document-equal
document-export
document-export-ocal
document-export-table
document-import
document-import-ocal
documentinfo
document-multiple
document-new
document-new-from-template
document-new-symbolic
document-open
document-open-data
document-open-folder
document-open-recent
document-open-recent-symbolic
document-open-remote
document-open-symbolic
document-page-setup-symbolic
document-preview
document-preview-archive
document-print
document-print-direct
document-print-frame
document-print-preview
document-print-preview-symbolic
document-print-symbolic
document-properties
document-properties-symbolic
document-replace
document-revert
document-revert-symbolic
document-revert-symbolic-rtl
document-save
document-save-all
document-save-as
document-save-as-symbolic
document-save-as-template
document-save-symbolic
document-scan
document-send
document-send-symbolic
document-share
document-sign
document-single
document-swap
document-unequal
donate
dontknow
download
download-amarok
download-later
drag-handle-symbolic
dragonplayer
drag-surface
draw-arrow
draw-arrow-back
draw-arrow-down
draw-arrow-forward
draw-arrow-up
draw-bezier-curves
draw-brush
draw-calligraphic
draw-circle
draw-connector
draw-cross
draw-cuboid
draw-donut
draw-ellipse
draw-ellipse-arc
draw-ellipse-segment
draw-ellipse-whole
draw-eraser
draw-eraser-delete-objects
draw-freehand
draw-halfcircle1
draw-halfcircle2
draw-halfcircle3
draw-halfcircle4
draw-highlight
draw-line
draw-number
draw-path
draw-polygon
draw-polygon-star
draw-polyline
draw-rectangle
draw-rectangle-rounded
draw-spiral
draw-square-inverted-corners
draw-star
draw-text
draw-triangle
draw-triangle1
draw-triangle2
draw-triangle3
draw-triangle4
draw-watercolor
drink-beer
drink-martini
drive-harddisk
drive-harddisk-encrypted
drive-harddisk-encrypted-symbolic
drive-harddisk-ieee1394-symbolic
drive-harddisk-root
drive-harddisk-root-symbolic
drive-harddisk-symbolic
drive-harddisk-system-symbolic
drive-harddisk-usb-symbolic
drive-multidisk
drive-multidisk-symbolic
drive-multipartition
drive-multipartition-symbolic
drive-optical
drive-partition
drive-partition-symbolic
drive-removable-media
drive-removable-media-symbolic
drive-removable-media-usb
drive-removable-media-usb-pendrive
dropboxstatus-busy
dropboxstatus-busy2
dropboxstatus-idle
dropboxstatus-logo
dropboxstatus-x
dvipdf
dvipng
dvips
dvisearch
dynamic-amarok
earthquake
edit_animation
edit-bomb
edit-clear
edit-clear-all
edit-clear-all-symbolic
edit-clear-history
edit-clear-list
edit-clear-locationbar-ltr
edit-clear-locationbar-rtl
edit-clear-rtl-symbolic
edit-clear-symbolic
edit-clear-symbolic-rtl
edit-clone
edit-clone-unlink
edit-comment
edit-copy
edit-copy-path
edit-copy-symbolic
edit-cut
edit-cut-symbolic
edit-delete
edit-delete-remove
edit-delete-shred
edit-delete-symbolic
edit-download
edit-duplicate
edit-entry
edit-find
edit-find-mail
edit-find-project
edit-find-replace
edit-find-replace-symbolic
edit-find-symbolic
edit-find-user
edit-group
edit-guides
edit-image
editimage
edit-image-face-add
edit-image-face-detect
edit-image-face-recognize
edit-image-face-show
edit-line-width
edit-link
edit-map
edit-move
edit-move-symbolic
edit-node
edit-none
edit-opacity
editor
edit-paste
edit-paste-in-place
edit-paste-style
edit-paste-symbolic
editpath
edit-redo
edit-redo-rtl-symbolic
edit-redo-symbolic
edit-redo-symbolic-rtl
edit-rename
edit-reset
edit-select
edit-select-all
edit-select-all-layers
edit-select-all-symbolic
edit-select-invert
edit-select-lasso
edit-select-none
edit-select-original
edit-select-symbolic
edit-select-text
edit-symbolic
edit-table-cell-merge
edit-table-cell-split
edit-table-delete-column
edit-table-delete-row
edit-table-insert-column-left
edit-table-insert-column-right
edit-table-insert-row-above
edit-table-insert-row-below
edit-table-insert-row-under
edittext
edit-text-frame-update
edit-undo
edit-undo-history
edit-undo-rtl-symbolic
edit-undo-symbolic
edit-undo-symbolic-rtl
elisa
ellipse-shape
emacs
emblem-added
emblem-checked
emblem-default-symbolic
emblem-documents-symbolic
emblem-encrypted-locked
emblem-encrypted-unlocked
emblem-error
emblem-favorite
emblem-favorite-symbolic
emblem-important
emblem-important-symbolic
emblem-information
emblem-locked
emblem-mounted
emblem-music-symbolic
emblem-ok-symbolic
emblem-pause
emblem-photos-symbolic
emblem-question
emblem-readonly
emblem-remove
emblem-shared
emblem-shared-symbolic
emblem-success
emblem-symbolic-link
emblem-synchronizing-symbolic
emblem-system-symbolic
emblem-unavailable
emblem-unlocked
emblem-unmounted
emblem-videos-symbolic
emblem-warning
embosstool
emph
empty
encrypted
end_of_life
end_state
entity
entrance_animations
entry-clone
entry-delete
entry-edit
entry-new
enum
enumerate
error
errornext
errorprev
escape-direction-all
escape-direction-down
escape-direction-horizontal
escape-direction-left
escape-direction-right
escape-direction-up
escape-direction-vertical
exception
exchange-positions
exchange-positions-clockwise
exchange-positions-zorder
exifinfo
exit_animations
expand
expand-all
expand-all-symbolic
export-symbolic
extension-symbolic
face-angel
face-angry
face-clown
face-confused
face-cool
face-crying
face-devilish
face-embarrassed
face-glasses
face-hug-left
face-hug-right
face-in-love
face-kiss
face-laughing
face-ninja
face-pirate
face-plain
face-quiet
face-raspberry
face-sad
face-sick
face-sleeping
face-smile
face-smile-big
face-smile-grin
face-smirk
face-surprise
face-uncertain
face-wink
face-worried
face-yawn
falkon
favorite
favorite-genres-amarok
favorites
fcitx-googlepinyin
fcitx-pinyin
fcitx-pinyin-libpinyin
fcitx-shuangpin
fcitx-shuangpin-libpinyin
fcitx-sunpinyin
fcitx-wubi
feed-subscribe
ffmulticonverter
file-catalog-symbolic
filegrep
file-library-symbolic
filelight
filename-album-amarok
filename-and-amarok
filename-artist-amarok
filename-bpm-amarok
filename-comment-amarok
filename-composer-amarok
filename-dash-amarok
filename-discnumber-amarok
filename-divider
filename-dot-amarok
filename-filetype-amarok
filename-genre-amarok
filename-group-length
filename-group-tracks
filename-ignore-amarok
filename-initial-amarok
filename-last-played
filename-moodbar
filename-sample-rate
filename-slash-amarok
filename-space-amarok
filename-title-amarok
filename-track-amarok
filename-underscore-amarok
filename-year-amarok
file-search-symbolic
fileview-preview
filezilla
file-zoom-in
file-zoom-out
fill-color
fill-rule-even-odd
fill-rule-nonzero
filmgrain
filter-symbolic
final_activity
financial-account
financial-budget
financial-categories
financial-forecast
financial-investments
financial-list
financial-payees
financial-report
financial-schedule
find-location
find-location-symbolic
fingerprint
fingerprint-gui
firewall-applet
firewall-applet-error
firewall-applet-panic
firewall-applet-shields_up
firewall-config
flag
flag-black
flag-blue
flag-green
flag-red
flag-yellow
flameshot-tray
flash
flashlight-off
flashlight-on
flow
flower-shape
fluid
folder
folder-activities
folder-add
folder-android
folder-appimage
folder-black
folder-blender
folder-blue
folder-book
folder-bookmark
folder-brown
folder-build
folder-calculate
folder-chart
folder-cloud
folder-comic
folder-crash
folder-cyan
folder-database
folder-deb
folder-decrypted
folder-design
folder-desktop
folder-development
folder-docker
folder-documents
folder-documents-symbolic
folder-download
folder-downloads
folder-download-symbolic
folder-drawing
folder-dropbox
folder-encrypted
folder-extension
folder-favorites
folder-flatpak
folder-games
folder-games-symbolic
folder-gdrive
folder-git
folder-godot
folder-green
folder-grey
folder-html
folder_html
folder-image
folder-image-people
folder-images
folder-important
folder-java
folder-language
folder-library
folder-locked
folder-log
folder-mac
folder-magenta
folder-mail
folder-music
folder-music-symbolic
folder-network
folder-new
folder-new-symbolic
folder-notes
folder-onedrive
folder-open
folder-open-recent
folder-open-symbolic
folder-orange
folder-owncloud
folder-paint
folder-picture
folder-pictures
folder-pictures-symbolic
folder-podcast
folder-presentation
folder-print
folder-public
folder-publicshare
folder-publicshare-symbolic
folder-recent
folder-red
folder-remote
folder-remote-symbolic
folder-root
folder-root-symbolic
folder-rpm
folder-saved-search-symbolic
folder-script
folder-sign
folder-snap
folder-sound
folder-stash
folder-symbolic
folder-sync
folder-table
folder-tar
folder-temp
folder-templates
folder-templates-symbolic
folder-text
folder-trash
folder-txt
folder-unlocked
folder-video
folder-videos
folder-videos-symbolic
folder-violet
folder-windows
folder-yellow
followmouse
font
font-disable
font-enable
font-face
fontforge
font-otf
font-select-symbolic
font-size-down
font-size-up
fonts-package
font-ttf
food
food-cake
foreign_green
foreignkey_constraint
foreign_red
fork
format-add-node
format-align-vertical-bottom
format-align-vertical-center
format-align-vertical-top
format-border-set-all
format-border-set-bottom
format-border-set-diagonal-bl-tr
format-border-set-diagonal-tl-br
format-border-set-external
format-border-set-internal
format-border-set-internal-horizontal
format-border-set-internal-vertical
format-border-set-left
format-border-set-none
format-border-set-right
format-border-set-top
format-border-style
format-break-node
format-connect-node
format-convert-to-path
format-currency
format-disconnect-node
format-fill-color
format-font-size-less
format-font-size-more
format-indent-less
format-indent-less-rtl-symbolic
format-indent-less-symbolic
format-indent-less-symbolic-rtl
format-indent-more
format-indent-more-rtl-symbolic
format-indent-more-symbolic
format-indent-more-symbolic-rtl
format-insert-node
format-join-node
format-justify-center
format-justify-center-symbolic
format-justify-fill
format-justify-fill-symbolic
format-justify-left
format-justify-left-symbolic
format-justify-right
format-justify-right-symbolic
format-line-spacing-double
format-line-spacing-normal
format-line-spacing-triple
format-list-ordered
format-list-unordered
format-node-corner
format-node-curve
format-node-line
format-node-smooth
format-node-symmetric
format-number-percent
format-precision-less
format-precision-more
format-remove-node
format-segment-curve
format-segment-line
format-stroke-color
format-text-blockquote
format-text-bold
format-text-bold-symbolic
format-text-capitalize
format-text-code
format-text-color
format-text-direction-horizontal
format-text-direction-ltr
format-text-direction-ltr-symbolic
format-text-direction-rtl
format-text-direction-rtl-symbolic
format-text-direction-symbolic
format-text-direction-symbolic-rtl
format-text-direction-vertical
format-text-italic
format-text-italic-symbolic
format-text-lowercase
format-text-strikethrough
format-text-strikethrough-symbolic
format-text-subscript
format-text-superscript
format-text-symbol
format-text-underline
format-text-underline-squiggle
format-text-underline-symbolic
format-text-uppercase
formula
freemind
freerotation
frostwire
games-achievements
games-config-background
games-config-board
games-config-custom
games-config-options
games-config-theme
games-config-tiles
games-difficult
games-endturn
games-highscores
games-hint
games-solve
gcompris-qt
geany-build
geany-close-all
geany-save-all
gearhead-shape
generalisation
generalise
get-hot-new-stuff
gimp
git-cola
git-gui
globe
gnumeric-autofilter
gnumeric-autofilter-delete
gnumeric-autosum
gnumeric-brush
gnumeric-bucket
gnumeric-cells-merge
gnumeric-cells-split
gnumeric-column-add
gnumeric-column-delete
gnumeric-column-hide
gnumeric-column-size
gnumeric-column-unhide
gnumeric-comment-add
gnumeric-comment-delete
gnumeric-comment-edit
gnumeric-component-insert-shaped
gnumeric-data-slicer
gnumeric-font
gnumeric-format-accounting
gnumeric-format-border-all
gnumeric-format-border-bottom
gnumeric-format-border-diag
gnumeric-format-border-double-bottom
gnumeric-format-border-inside-horiz
gnumeric-format-border-left
gnumeric-format-border-none
gnumeric-format-border-outside
gnumeric-format-border-rev-diag
gnumeric-format-border-right
gnumeric-format-border-thick-bottom
gnumeric-format-border-thick-outside
gnumeric-format-border-top
gnumeric-format-border-top-n-bottom
gnumeric-format-border-top-n-double-bottom
gnumeric-format-border-top-n-thick-bottom
gnumeric-format-halign-distributed
gnumeric-format-percentage
gnumeric-format-precision-decrease
gnumeric-format-precision-increase
gnumeric-format-thousand-separator
gnumeric-format-valign-bottom
gnumeric-format-valign-center
gnumeric-format-valign-distributed
gnumeric-format-valign-justify
gnumeric-format-valign-top
gnumeric-formulaguru
gnumeric-graphguru
gnumeric-group
gnumeric-link-add
gnumeric-link-delete
gnumeric-link-edit
gnumeric-link-email
gnumeric-link-external
gnumeric-link-internal
gnumeric-link-url
gnumeric-object-arrow
gnumeric-object-button
gnumeric-object-checkbox
gnumeric-object-combo
gnumeric-object-ellipse
gnumeric-object-label
gnumeric-object-line
gnumeric-object-list
gnumeric-object-rectangle
gnumeric-object-scrollbar
gnumeric-object-spinbutton
gnumeric-pagesetup-hf-cell
gnumeric-pagesetup-hf-page
gnumeric-pagesetup-hf-pages
gnumeric-pagesetup-hf-time
gnumeric-pivottable
gnumeric-protection-no
gnumeric-protection-yes
gnumeric-row-add
gnumeric-row-delete
gnumeric-row-hide
gnumeric-row-size
gnumeric-row-unhide
gnumeric-subscript
gnumeric-superscript
gnumeric-ungroup
gnumeric-visible
go-bottom
go-bottom-symbolic
go-down
go-down-search
go-down-skip
go-down-symbolic
go-first
go-first-rtl-symbolic
go-first-symbolic
go-first-symbolic-rtl
go-first-view
go-first-view-page
go-home
go-home-large
go-home-symbolic
go-jump
go-jump-declaration
go-jump-definition
go-jump-locationbar
go-jump-rtl-symbolic
go-jump-symbolic
go-jump-today
go-last
go-last-rtl-symbolic
go-last-symbolic
go-last-symbolic-rtl
go-last-view
go-last-view-page
go-next
go-next-context
go-next-rtl-symbolic
go-next-skip
go-next-symbolic
go-next-symbolic-rtl
go-next-use
go-next-view
go-next-view-page
goodvibes
go-parent-folder
go-previous
go-previous-context
go-previous-rtl-symbolic
go-previous-skip
go-previous-symbolic
go-previous-symbolic-rtl
go-previous-use
go-previous-view
go-previous-view-page
go-top
go-top-symbolic
go-up
go-up-search
go-up-skip
go-up-symbolic
gpg
gpgsm
gpick
gpodder
gps
gradient
granatier
graphics
graphics-viewer-document
grid-axonometric
grid-rectangular
group
group-delete
group-edit
group-new
grub-customizer
gtk-add
gtk-apply
gtk-authentication
gtk-bold
gtk-cancel
gtk-cdrom
gtk-clear
gtk-close
gtk-color-picker
gtkconfig
gtk-connect
gtk-convert
gtk-disconnect
gtk-edit
gtk-execute
gtk-floppy
gtkhash
gtk-index
gtk-no
gtk-ok
gtk-preferences
gtk-properties
gtk-quit
gtk-select-color
gtk-select-font
gtk-stop
gtk-tab-duplicate
gtk-tab-new
gtk-undelete-ltr
gtk-undelete-rtl
gtk-yes
guides
gwenview
haguichi
haguichi-connected
haguichi-connecting-1
haguichi-connecting-2
haguichi-connecting-3
haguichi-disconnected
hand
handbrake
handle-left
handle-move
handle-right
handle-sort
handset
hands-free
headphone
headphones
headset
help-about
help-about-symbolic
help-browser
help-contents
help-contextual
help-donate
help-donate-ars
help-donate-aud
help-donate-brl
help-donate-cad
help-donate-chf
help-donate-cny
help-donate-eur
help-donate-gbp
help-donate-inr
help-donate-jpy
help-donate-mxn
help-donate-pln
help-donate-rub
help-donate-sek
help-donate-try
help-donate-uah
help-donate-usd
help-feedback
help-hint
help-keybord-shortcuts
help-latex
help-whatsthis
hexagon-shape
hidemouse
hide_table_column
hide_table_row
hifi
high-brightness
highlight-pointer-spot
hint
histogram-symbolic
home
homebank
homerun
hotpixels
hotspot
htop
hwinfo
identity
image-bmp
imagecomment
image-crop-symbolic
image-flip-horizontal-symbolic
image-flip-vertical-symbolic
image-gif
image-ico
image-invert-symbolic
image-jpeg
image-jpeg2000
image-loading-symbolic
image-missing
image-navigator-symbolic
image-png
image-red-eye-symbolic
image-resize-symbolic
image-rotate-left-symbolic
image-rotate-right-symbolic
image-rotate-symbolic
image-tiff
image-vnd.dgn
image-vnd.djvu
image-vnd.dwg
image-vnd.microsoft.icon
imagewriter
image-x-adobe-dng
image-x-compressed-xcf
image-x-emf
image-x-eps
image-x-generic
image-x-ico
image-x-icon
image-x-krita
image+xml-compressed.svg
image+xml.svg
image-x-portable-bitmap
image-x-psd
image-x-psdimage-x-psd
image-x-tga
image-x-vnd.trolltech.qpicture
image-x-win-bitmap
image-x-win-bmp
image-x-wmf
image-x-xcf
image-x-xfig
image-x+xml.svg
im-aim
im-ban-kick-user
im-ban-user
im-facebook
im-gadugadu
im-google
im-google-talk
im-icq
im-identi.ca
im-invisible-user
im-irc
im-jabber
im-kick-user
im-msn
im-qq
im-skype
im-twitter
im-user
im-user-away
im-user-busy
im-user-offline
im-user-online
im.vector
im-yahoo
im-youtube
Info-amarok
initial_state
inkscape
inkscape-logo
inode-directory
inpainting
input-caps-on
input-dialpad
input-dialpad-symbolic
input-gamepad
input-gamepad-symbolic
input-gaming
input-keyboard
input-keyboard-symbolic
input-keyboard-virtual
input-keyboard-virtual-hide
input-keyboard-virtual-off
input-keyboard-virtual-on
input-keyboard-virtual-show
input-keyboard-virtual-symbolic
input-mouse
input-mouse-click-left
input-mouse-click-middle
input-mouse-click-right
input-mouse-symbolic
input-tablet
input-tablet-symbolic
input-touchpad
input-touchpad-off
input-touchpad-on
input-touchpad-symbolic
input-touchscreen
input-tvremote
insert-button
insertcell
insertcellcopy
insert-endnote
insert-footnote
insert-horizontal-rule
insert-image
insert-image-symbolic
insert-link
insert-link-symbolic
insert-math-expression
insert-more-mark
insert-page-break
insert-table
insert-table-of-contents
insert-tableofcontents
insert-table-row
insert-text
insert-text-frame
insert-text-symbolic
install
installed
institution
interface
internal
internet-amarok
internet-mail
internet-services
internet-telephony
internet-web-browser
invertimage
io.gitlab.Goodvibes
irc-channel-active
irc-channel-inactive
irc-channel-joined
irc-channel-parted
irc-close-channel
irc-join-channel
irc-operator
irc-remove-operator
irc-unvoice
irc-voice
item
itemize
jdownloader
join
joplin
journal-new
juk
juliabackend
junction
k3b
kaccess
kaddressbook
kaffeine
kajongg
kalarm
kalgebra
kalgebrabackend
kalzium
kamoso
kanagram
kapman
kapptemplate
karbon
kate
katomic
kblackbox
kblocks
kblogger
kbreakout
kbruch
kcachegrind
kcalc
kchart
kcolorchooser
kde
kdeapp
kdeconnect
kdeconnect-tray
kded5
kde-frameworks
kde-gtk-config
kde-im-log-viewer
kdenlive
kdenlive-add-clip
kdenlive-add-color-clip
kdenlive-add-slide-clip
kdenlive-add-text-clip
kdenlive-align-bottom
kdenlive-align-hor
kdenlive-align-left
kdenlive-align-none
kdenlive-align-right
kdenlive-align-top
kdenlive-align-vert
kdenlive-composite
kdenlive-custom-effect
kdenlive-deleffect
kdenlive-down
kdenlive-hide-audio
kdenlive-hide-video
kdenlive-insert-edit
kdenlive-insert-rect
kdenlive-insert-unicode
kdenlive-lock
kdenlive-menu
kdenlive-no-composite
kdenlive-normal-edit
kdenlive-object-height
kdenlive-object-width
kdenlive-overwrite-edit
kdenlive-ripple
kdenlive-rolling
kdenlive-select-all
kdenlive-select-images
kdenlive-select-rects
kdenlive-select-texts
kdenlive-select-tool
kdenlive-show-audio
kdenlive-show-audiothumb
kdenlive-show-markers
kdenlive-show-video
kdenlive-show-videothumb
kdenlive-slide
kdenlive-slip
kdenlive-snap
kdenlive-spacer-tool
kdenlive-split-audio
kdenlive-track_has_effect
kdenlive-unlock
kdenlive-unselect-all
kdenlive-up
kdenlive-zindex-bottom
kdenlive-zindex-down
kdenlive-zindex-top
kdenlive-zindex-up
kdenlive-zone-end
kdenlive-zone-start
kdenlive-zoom-large
kdenlive-zoom-small
kdesrc-build
kdesvn
kdevelop
kdiamond
kdiff3
kdocumentinfo
kdots
keepass
keepass2
keepassx
keepassx2
kexi
keyboard-caps-disabled
keyboard-caps-enabled
keyboard-caps-locked
keyboard-enter
keyboard-spacebar
key-enter
keyframe
keyframe-add
keyframe-disable
keyframe-duplicate
keyframe-next
keyframe-previous
keyframe-record
keyframe-remove
kfind
kfloppy
kfontview
kfourinline
kgeography
kget
khangman
kig
kile
kimagemapeditor
kipi-dngconverter
kipi-expoblending
kipi-panorama
kirigami-gallery
kiriki
kirogi
kiten
kjumpingcube
kleopatra
klines
klipper
kmag
kmahjongg
kmail
kmenuedit
kmix
kmousetool
kmousetool_off
kmousetool_on
kmouth
kmouth-phrase
kmouth-phrasebook
kmouth-phrase-new
kmouth-phresebook-new
kmplayer
kmplot
kmymoney
knetattach
knights
knotes
knotes_alarm
knotes_date
knotes_delete
know
kolf
kolourpaint
kompare
konqueror
kontact
kontact-import-wizard
kontes_close
konversation
kopete
korgac
korganizer
korg-todo
kpat
kphotoalbum
kplato
kpresenter
kr_combine
kr_comparedirs
krdc
kr_diskusage
krename
krfb
kr_jumpback
kr_mountman
kronometer
kr_setjumpback
kr_syncbrowse_off
kr_syncbrowse_on
kruler
kruler-east
kruler-north
kruler-south
kruler-west
krunner
kr_unselect
krusader_root
krusader_user
kshisen
ksirk
ksmserver
ksnapshot
kspread
kstars
kstars_advanced
kstars_catalog
kstars_cbound
kstars_clines
kstars_cnames
kstars_colors
kstars_constellationart
kstars_deepsky
kstars_ekos
kstars_fitsviewer
kstars_flag
kstars_grid
kstars_guides
kstars_hgrid
kstars_horizon
kstars_indi
kstars_mw
kstars_planets
kstars_satellites
kstars_solarsystem
kstars_stars
kstars_supernovae
kstars_xplanet
ksysguardd
kt-add-feeds
kt-add-filters
kt-bandwidth-scheduler
kt-change-tracker
kt-check-data
kt-chunks
kteatime
kt-encrypted
ktimer
ktimetracker
kt-info-widget
ktip
kt-magnet
ktnef
ktnef_extract_all_to
ktnef_extract_to
ktorrent
ktouch
kt-pause
kt-plugins
kt-queue-manager
kt-remove
kt-remove-feeds
kt-remove-filters
kt-restore-defaults
ktrip
kt-set-max-download-speed
kt-set-max-upload-speed
kt-show-statusbar
kt-speed-limits
kt-start
kt-start-all
kt-stop
kt-stop-all
kube-mail
kuiviewer
kup
kuser
kwalletmanager
kwalletmanager2
kwave
kwin
kword
kwrite
kxstitch
l2h
label
label-amarok
labplot
labplot-1x-zoom
labplot2
labplot-2x-zoom
labplot-3x-zoom
labplot-4x-zoom
labplot-5x-zoom
labplot-auto-scale-all
labplot-auto-scale-x
labplot-auto-scale-y
labplot-axis-horizontal
labplot-axis-vertical
labplot-cursor-arrow
labplot-editbreaklayout
labplot-editgrid
labplot-edithlayout
labplot-editvlayout
labplot-format-text-symbol
labplot-matrix
labplot-matrix-new
labplot-plot-axis-points
labplot-shift-down-y
labplot-shift-left-x
labplot-shift-right-x
labplot-shift-up-y
labplot-spreadsheet
labplot-spreadsheet-new
labplot-TeX-logo
labplot-transform-move
labplot-workbook
labplot-workbook-new
labplot-worksheet
labplot-worksheet-new
labplot-xy-curve
labplot-xy-curve-points
labplot-xy-curve-segments
labplot-xy-equation-curve
labplot-xy-fit-curve
labplot-xy-fourier-filter-curve
labplot-xy-fourier-transform-curve
labplot-xy-interpolation-curve
labplot-xy-plot-four-axes
labplot-xy-plot-two-axes
labplot-xy-plot-two-axes-centered
labplot-xy-plot-two-axes-centered-origin
labplot-xy-smoothing-curve
labplot-zoom-in-x
labplot-zoom-in-y
labplot-zoom-out-x
labplot-zoom-out-y
labplot-zoom-select
labplot-zoom-select-x
labplot-zoom-select-y
language-chooser
languages
lastfm-neighbour
lastfm-personal
lastfm-recommended
lastfm-tag
lastpass
latex
latex-config
latte-dock
layer-bottom
layer-delete
layer-duplicate
layer-lower
layer-new
layer-next
layer-previous
layer-raise
layer-rename
layer-top
layer-visible-off
layer-visible-on
lensautofix
lensdistortion
leocad
libpeas-plugin
library-music
libreoffice-base
libreoffice-calc
libreoffice-database
libreoffice-draw
libreoffice-drawing
libreoffice-drawing-template
libreoffice-extension
libreoffice-formula
libreoffice-impress
libreoffice-main
libreoffice-master-document
libreoffice-math
libreoffice-oasis-database
libreoffice-oasis-drawing
libreoffice-oasis-drawing-template
libreoffice-oasis-formula
libreoffice-oasis-master-document
libreoffice-oasis-presentation
libreoffice-oasis-presentation-template
libreoffice-oasis-spreadsheet
libreoffice-oasis-spreadsheet-template
libreoffice-oasis-text
libreoffice-oasis-text-template
libreoffice-oasis-web-template
libreoffice-presentation
libreoffice-presentation-template
libreoffice-spreadsheet
libreoffice-spreadsheet-template
libreoffice-startcenter
libreoffice-text
libreoffice-text-template
libreoffice-writer
license
lighttable
lighttableadd
lilypond
linear
lines-connector
linguist
link
list-add
list-add-font
list-add-symbolic
list-add-user
list-remove
list-remove-all-symbolic
list-remove-symbolic
list-remove-user
list-resource-add
lock
logisim
lokalize
love
love-amarok
low-brightness
luabackend
mail-attachment
mail-attachment-symbolic
mail-client
mail-deleted
mail-download-later
mail-download-now
mail-encrypted
mail-encrypted-full
mail-encrypted-part
mail-flag
mail-folder-inbox
mail-folder-outbox
mail-folder-sent
mail-forward
mail-forward-attachment
mail-forward-custom
mail-forwarded
mail-forwarded-replied
mail-forward-symbolic
mail-inbox-symbolic
mail-invitation
mail-mark-important
mail-mark-important-symbolic
mail-mark-junk
mail-mark-notjunk
mail-mark-read
mail-mark-task
mail-mark-unread
mail-mark-unread-new
mail-meeting-request-reply
mail-message
mail-message-new
mail-message-new-list
mail-message-new-symbolic
mail-outbox-symbolic
mail-queue
mail-queued
mail-read
mail-read-symbolic
mail-receive
mail-replied
mail-replied-symbolic
mail-reply-all
mail-reply-all-symbolic
mail-reply-author
mail-reply-custom
mail-reply-custom-all
mail-reply-list
mail-reply-sender
mail-reply-sender-symbolic
mail-send
mail-send-receive-symbolic
mail-send-symbolic
mail-sent
mail-sent-symbolic
mail-signature-unknown
mail-signed
mail-signed-full
mail-signed-fully
mail-signed-part
mail-signed-verified
mail-tagged
mail-task
mail-thread-ignored
mail-thread-watch
mail-unread
mail-unread-new
mail-unread-symbolic
makeidx
map-flat
map-globe
map-gnomonic
map-mercator
map-symbolic
markasblank
mark-location
mark-location-symbolic
massif-visualizer
masterpdfeditor
math0
math1
math2
math3
math7
math9
mathematica
mathmode
matlab
maximabackend
measure
media-album-cover
media-album-cover-manager-amarok
media-album-repeat-amarok
media-album-track
mediacontrol
media-default-album
media-default-track
media-eject
media-eject-symbolic
media-flash
media-flash-memory-stick
media-flash-sd-mmc
media-flash-smart-media
media-flash-symbolic
media-floppy
media-floppy-symbolic
media-import-audio-cd
media-mount
media-optical
media-optical-audio
media-optical-bd-symbolic
media-optical-blu-ray
media-optical-cd-audio-symbolic
media-optical-data
media-optical-dvd
media-optical-dvd-symbolic
media-optical-mixed-cd
media-optical-recordable
media-optical-symbolic
media-optical-video
media-playback-pause
media-playback-paused
media-playback-pause-symbolic
media-playback-playing
media-playback-start
media-playback-start-rtl-symbolic
media-playback-start-symbolic
media-playback-start-symbolic-rtl
media-playback-stop
media-playback-stopped
media-playback-stop-symbolic
media-playlist-append
media-playlist-consecutive-symbolic
media-playlist-consecutive-symbolic-rtl
media-playlist-normal
media-playlist-play
media-playlist-repeat
media-playlist-repeat-amarok
media-playlist-repeat-song
media-playlist-repeat-song-symbolic
media-playlist-repeat-song-symbolic-rtl
media-playlist-repeat-symbolic
media-playlist-repeat-symbolic-rtl
media-playlist-shuffle
media-playlist-shuffle-symbolic
media-playlist-shuffle-symbolic-rtl
media-random-albums-amarok
media-random-tracks-amarok
media-record
media-record-symbolic
media-removable-symbolic
media-repeat-album-amarok
media-repeat-all
media-repeat-none
media-repeat-playlist-amarok
media-repeat-single
media-repeat-track-amarok
media-seek-backward
media-seek-backward-rtl-symbolic
media-seek-backward-symbolic
media-seek-backward-symbolic-rtl
media-seek-forward
media-seek-forward-rtl-symbolic
media-seek-forward-symbolic
media-seek-forward-symbolic-rtl
media-show-active-track-amarok
media-skip-backward
media-skip-backward-rtl-symbolic
media-skip-backward-symbolic
media-skip-backward-symbolic-rtl
media-skip-forward
media-skip-forward-rtl-symbolic
media-skip-forward-symbolic
media-skip-forward-symbolic-rtl
media-standard-track-progression-amarok
media-track-add-amarok
media-track-edit-amarok
media-track-queue-amarok
media-track-remove-amarok
media-track-show-active
media-view-subtitles-symbolic
media-write-cd
media-write-dvd
medskip
meeting-attending
meeting-attending-tentative
meeting-organizer
meeting-participant-no-response
meeting-participant-request-response
mendeleydesktop
menu_new
menu_new_sep
merge
mergecell
mergecell-horizontal
mergecell-vertical
message
messagebox_warning
message-new
message-news
message-partial
message-rfc822
message-x-gnu-rmail
mic-off
mic-on
mic-ready
microphone
microphone-sensitivity-high
microphone-sensitivity-high-symbolic
microphone-sensitivity-low
microphone-sensitivity-low-symbolic
microphone-sensitivity-medium
microphone-sensitivity-medium-symbolic
microphone-sensitivity-muted
microphone-sensitivity-muted-symbolic
milestone
minitube
minuet
minuet-chords
minuet-intervals
minuet-rhythms
minuet-scales
mixxx
mode1
mode2
mode3
mode4
mode5
modified
monitor
motion_path_animations
mpost
mpv
msgid2msgstr
multimedia-player
multimedia-player-apple-ipod-touch-symbolic
multimedia-player-ipod-mini-blue
multimedia-player-symbolic
multimedia-volume-control
multiple
multirow
muon
muondiscover
music-amarok
music-note-16th
network-bluetooth
network-bluetooth-activated
network-bluetooth-activated-locked
network-card
network-connect
network-disconnect
network-flightmode-off
network-flightmode-on
network-limited
network-manager
network-mobile-0
network-mobile-0-edge
network-mobile-0-edge-locked
network-mobile-0-gprs
network-mobile-0-gprs-locked
network-mobile-0-hsdpa
network-mobile-0-hsdpa-locked
network-mobile-0-hspa
network-mobile-0-hspa-locked
network-mobile-0-hsupa
network-mobile-0-hsupa-locked
network-mobile-0-locked
network-mobile-0-lte
network-mobile-0-lte-locked
network-mobile-0-umts
network-mobile-0-umts-locked
network-mobile-100
network-mobile-100-edge
network-mobile-100-edge-locked
network-mobile-100-gprs
network-mobile-100-gprs-locked
network-mobile-100-hsdpa
network-mobile-100-hsdpa-locked
network-mobile-100-hspa
network-mobile-100-hspa-locked
network-mobile-100-hsupa
network-mobile-100-hsupa-locked
network-mobile-100-locked
network-mobile-100-lte
network-mobile-100-lte-locked
network-mobile-100-umts
network-mobile-100-umts-locked
network-mobile-20
network-mobile-20-edge
network-mobile-20-edge-locked
network-mobile-20-gprs
network-mobile-20-gprs-locked
network-mobile-20-hsdpa
network-mobile-20-hsdpa-locked
network-mobile-20-hspa
network-mobile-20-hspa-locked
network-mobile-20-hsupa
network-mobile-20-hsupa-locked
network-mobile-20-locked
network-mobile-20-lte
network-mobile-20-lte-locked
network-mobile-20-umts
network-mobile-20-umts-locked
network-mobile-40
network-mobile-40-edge
network-mobile-40-edge-locked
network-mobile-40-gprs
network-mobile-40-gprs-locked
network-mobile-40-hsdpa
network-mobile-40-hsdpa-locked
network-mobile-40-hspa
network-mobile-40-hspa-locked
network-mobile-40-hsupa
network-mobile-40-hsupa-locked
network-mobile-40-locked
network-mobile-40-lte
network-mobile-40-lte-locked
network-mobile-40-umts
network-mobile-40-umts-locked
network-mobile-60
network-mobile-60-edge
network-mobile-60-edge-locked
network-mobile-60-gprs
network-mobile-60-gprs-locked
network-mobile-60-hsdpa
network-mobile-60-hsdpa-locked
network-mobile-60-hspa
network-mobile-60-hspa-locked
network-mobile-60-hsupa
network-mobile-60-hsupa-locked
network-mobile-60-locked
network-mobile-60-lte
network-mobile-60-lte-locked
network-mobile-60-umts
network-mobile-60-umts-locked
network-mobile-80
network-mobile-80-edge
network-mobile-80-edge-locked
network-mobile-80-gprs
network-mobile-80-gprs-locked
network-mobile-80-hsdpa
network-mobile-80-hsdpa-locked
network-mobile-80-hspa
network-mobile-80-hspa-locked
network-mobile-80-hsupa
network-mobile-80-hsupa-locked
network-mobile-80-locked
network-mobile-80-lte
network-mobile-80-lte-locked
network-mobile-80-umts
network-mobile-80-umts-locked
network-mobile-available
network-mobile-off
network-mobile-on
network-modem
network-offline
network-offline-symbolic
network-rj11-female
network-rj45-female
network-server
network-server-database
network-server-symbolic
network-vpn
network-wired
network-wired-activated
network-wired-disconnected
network-wired-symbolic
network-wired-unavailable
network-wireless
network-wireless-acquiring
network-wireless-connected-00
network-wireless-connected-100
network-wireless-connected-25
network-wireless-connected-50
network-wireless-connected-75
network-wireless-disconnected
network-wireless-hotspot
network-wireless-signal-excellent
network-wireless-signal-good
network-wireless-signal-none
network-wireless-signal-ok
network-wireless-signal-weak
network-wireless-symbolic
network-workgroup
network-workgroup-symbolic
new-audio-alarm
new-command-alarm
newer
newline
news-subscribe
news-unsubscribe
nextfuzzy
nextfuzzyuntrans
nextuntranslated
nm-device-wired
nm-nm-signal-00
nm-nm-signal-100
nm-nm-signal-25
nm-nm-signal-50
nm-nm-signal-75
nm-no-connection
nocover
node
node-add
node-break
node-delete
node-delete-segment
node-join
node-join-segment
node-segment-curve
node-segment-line
node-transform
node-type-auto-smooth
node-type-cusp
node-type-smooth
node-type-symmetric
noisereduction
none
noninstalled
non-starred-symbolic
nota
note
notifications
notifications-disabled
nroot
ntfs-config
nylas
object
object-align-horizontal-center-calligra
object-align-horizontal-left-calligra
object-align-horizontal-right-calligra
object-align-vertical-bottom-calligra
object-align-vertical-bottom-top-calligra
object-align-vertical-center-calligra
object-align-vertical-top-calligra
object-columns
object-fill
object-flip-horizontal
object-flip-horizontal-symbolic
object-flip-vertical
object-flip-vertical-symbolic
object-group
object-group-calligra
object-hidden
object-locked
object_node
object-order-back
object-order-back-calligra
object-order-front
object-order-front-calligra
object-order-lower
object-order-lower-calligra
object-order-raise
object-order-raise-calligra
object-rotate-left
object-rotate-left-symbolic
object-rotate-right
object-rotate-right-symbolic
object-rows
object-select-symbolic
object-stroke
object-stroke-style
object-to-path
object-ungroup
object-ungroup-calligra
object-unlocked
object-visible
octave
octavebackend
octopi
odf
office-address-book
office-calendar
office-chart-area
office-chart-area-focus-peak-node
office-chart-area-percentage
office-chart-area-stacked
office-chart-bar
office-chart-bar-percentage
office-chart-bar-stacked
office-chart-line
office-chart-line-forecast
office-chart-line-percentage
office-chart-line-stacked
office-chart-pie
office-chart-polar
office-chart-polar-stacked
office-chart-ring
office-chart-scatter
office-report
offline
offline-settings
oilpaint
okteta
okular
online
openbravo-erp
open-for-editing
open-menu-symbolic
org.fedoraproject.AnacondaInstaller
org.gajim.Gajim
org.inkscape.Inkscape
org.kde.Ikona
org.kde.kongress
org.kde.kontrast
org.kde.ktpcontactlist
org.kde.muonnotifier
org.kde.neochat
org.kde.plasma.activitybar
org.kde.plasma.analogclock
org.kde.plasma.battery
org.kde.plasma.binaryclock
org.kde.plasma.calculator
org.kde.plasma.calendar
org.kde.plasma.clipboard
org.kde.plasma.colorpicker
org.kde.plasma.comic
org.kde.plasma.date
org.kde.plasma.devicenotifier
org.kde.plasma.digitalclock
org.kde.plasma.diskquota
org.kde.plasma.fifteenpuzzle
org.kde.plasma.folder
org.kde.plasma.frame
org.kde.plasma.fuzzyclock
org.kde.plasma.icontasks
org.kde.plasma.kicker
org.kde.plasma.kickerdash
org.kde.plasma.kickoff
org.kde.plasma.kickofflegacy
org.kde.plasma.mediacontroller
org.kde.plasma.networkmanagement
org.kde.plasma.notes
org.kde.plasma.pager
org.kde.plasma.quicklaunch
org.kde.plasma.showActivityManager
org.kde.plasma.systemloadviewer
org.kde.plasma.systemmonitor.cpu
org.kde.plasma.systemmonitor.diskactivity
org.kde.plasma.systemmonitor.diskusage
org.kde.plasma.systemmonitor.memory
org.kde.plasma.systemmonitor.net
org.kde.plasma.systemtray
org.kde.plasma.taskmanager
org.kde.plasma.timer
org.kde.plasma.userswitcher
org.kde.plasma.vault
org.kde.plasma.volume
org.kde.plasma.windowlist
org.kde.skanlite
org.telegram.desktop
org.xfce.gigolo
osd-duplicate
osd-rotate-ccw
osd-rotate-cw
osd-rotate-flip
osd-rotate-normal
osd-sbs-left
osd-sbs-sright
osd-shutd-laptop
osd-shutd-screen
outdated
output_win
overexposure
overflow-menu
overflow-menu-left
overflow-menu-right
package
package-available
package-available-locked
package-broken
package-downgrade
package-install
package-install-auto
package-installed-locked
package-installed-outdated
package-installed-updated
package-new
package-purge
package-reinstall
package-remove
package-remove-auto
package-upgrade
package-upgrade-auto
package-x-generic
page-2sides
page-3sides
page-4sides
page-simple
page-zoom
paint-gradient-linear
paint-gradient-radial
paint-none
paint-pattern
paint-solid
paint-swatch
paint-unknown
palette-symbolic
pan-down-symbolic
pan-end-symbolic
pan-end-symbolic-rtl
pan-start-symbolic
pan-start-symbolic-rtl
pan-up-symbolic
paper-color
parley
partitionmanager
password-copy
password-generate
password-show-off
password-show-on
path-break-apart
path-clip-edit
path-combine
path-cut
path-difference
path-division
path-effect-parameter-next
path-exclusion
path-inset
path-intersection
path-mask-edit
path-mode-bezier
path-mode-polyline
path-mode-polyline-paraxial
path-mode-spiro
path-offset-dynamic
path-offset-linked
path-outset
path-reverse
pathshape
path-simplify
path-union
pattern
pattern-basis
pattern-basis-addon
pattern-basis-devel
pattern-c-devel
pattern-cinnamon
pattern-deepin
pattern-documentation
pattern-e17
pattern-enlightenment
pattern-generic
pattern-gnome
pattern-gnome-devel
pattern-gnome-wayland
pattern-gnome-xorg
pattern-java-devel
pattern-kde
pattern-kde-addon
pattern-kde-devel
pattern-kubic
pattern-laptop
pattern-lxde
pattern-lxqt
pattern-mate
pattern-mono
pattern-obs-devel
pattern-perl-devel
pattern-python-devel
pattern-qt-devel
pattern-rpm-devel
pattern-ruby-devel
pattern-tcltk-devel
pattern-tests
pattern-xfce
pdf-annotations
pdflatex
pdftex
pentagon-shape
percent
perspective
phone
phone-apple-iphone-symbolic
phone-symbolic
phonon-gstreamer
photo
photolayoutseditor
photos-amarok
picmi
pidgin-tray-available
pidgin-tray-away
pidgin-tray-busy
pidgin-tray-email
pidgin-tray-invisible
pidgin-tray-offline
pidgin-tray-pending
pidgin-tray-xa
pin
pixelart-trace
plan
planetkde
plank
planner
planwork
plasma
plasma-browser-integration
plasmadiscover
plasmagik
plasma-media-center
plasma-mobile-phone
plasma-nano
plasma-search
plasmashell
plasmavault
player-time
player-volume
player-volume-muted
playlist-generator
playlist-sort
plugins
podcast
podcast-amarok
pointer
polygon-add-nodes
polygon-merge-nodes
port
portable
postalcode
practice-setup
practice-start
practice-stop
precondition
preferences
preferences-desktop
preferences-desktop-accessibility
preferences-desktop-activities
preferences-desktop-baloo
preferences-desktop-color
preferences-desktop-cryptography
preferences-desktop-cursors
preferences-desktop-default-applications
preferences-desktop-display
preferences-desktop-display-color
preferences-desktop-effects
preferences-desktop-emoticons
preferences-desktop-feedback
preferences-desktop-filetype-association
preferences-desktop-filter
preferences-desktop-font
preferences-desktop-font-installer
preferences-desktop-gaming
preferences-desktop-gestures-screenedges
preferences-desktop-gestures-touch
preferences-desktop-icons
preferences-desktop-keyboard
preferences-desktop-launch-feedback
preferences-desktop-locale
preferences-desktop-menu-edit
preferences-desktop-mouse
preferences-desktop-multimedia
preferences-desktop-navigation
preferences-desktop-notification
preferences-desktop-notification-bell
preferences-desktop-peripherals
preferences-desktop-plasma
preferences-desktop-plasma-theme
preferences-desktop-screensaver
preferences-desktop-search
preferences-desktop-sound
preferences-desktop-tablet
preferences-desktop-text-to-speech
preferences-desktop-theme
preferences-desktop-theme-applications
preferences-desktop-theme-global
preferences-desktop-theme-windowdecorations
preferences-desktop-thunderbolt
preferences-desktop-touchpad
preferences-desktop-touchscreen
preferences-desktop-user
preferences-desktop-user-password
preferences-desktop-virtual
preferences-desktop-wallpaper
preferences-devices-cpu
preferences-devices-drive-optical-check
preferences-devices-printer
preferences-devices-scanner
preferences-devices-tree
preferences-document
preferences-git
preferences-gtk-config
preferences-indicator-amarok
preferences-kde-connect
preferences-log
preferences-media-playback-amarok
preferences-online-accounts
preferences-other
preferences-other-symbolic
preferences-plugin
preferences-releasenotes
preferences-scroll
preferences-security
preferences-security-apparmor
preferences-security-firewall
preferences-security-kerberos
preferences-smart-status
preferences-system
preferences-system-backup
preferences-system-bluetooth
preferences-system-linux
preferences-system-login
preferences-system-network
preferences-system-network-dsl
preferences-system-network-ethernet
preferences-system-network-iscsi
preferences-system-network-ldap
preferences-system-network-nis
preferences-system-network-ntp
preferences-system-network-proxy
preferences-system-network-remote
preferences-system-network-server
preferences-system-network-server-boot
preferences-system-network-server-dhcp
preferences-system-network-server-dns
preferences-system-network-server-ftp
preferences-system-network-server-installation
preferences-system-network-server-iscsi
preferences-system-network-server-kerberos
preferences-system-network-server-ldap
preferences-system-network-server-mail
preferences-system-network-server-nis
preferences-system-network-server-share
preferences-system-network-server-share-windows
preferences-system-network-server-slp
preferences-system-network-server-web
preferences-system-network-share
preferences-system-network-share-windows
preferences-system-network-sharing
preferences-system-network-vpn
preferences-system-network-wakeonlan
preferences-system-performance
preferences-system-power-management
preferences-system-search-symbolic
preferences-system-services
preferences-system-session-services
preferences-system-splash
preferences-system-startup
preferences-system-symbolic
preferences-system-tabbox
preferences-system-time
preferences-system-users
preferences-system-user-sudo
preferences-system-windows
preferences-system-windows-actions
preferences-system-windows-behavior
preferences-system-windows-effect-blur
preferences-system-windows-effect-contrast
preferences-system-windows-effect-coverswitch
preferences-system-windows-effect-cubeslide
preferences-system-windows-effect-desktopgrid
preferences-system-windows-effect-dialog-parent
preferences-system-windows-effect-diminactive
preferences-system-windows-effect-dimscreen
preferences-system-windows-effect-fade
preferences-system-windows-effect-fadedesktop
preferences-system-windows-effect-fallapart
preferences-system-windows-effect-flipswitch
preferences-system-windows-effect-glide
preferences-system-windows-effect-highlightwindow
preferences-system-windows-effect-invert
preferences-system-windows-effect-kscreen
preferences-system-windows-effect-login
preferences-system-windows-effect-logout
preferences-system-windows-effect-magiclamp
preferences-system-windows-effect-magnifier
preferences-system-windows-effect-maximize
preferences-system-windows-effect-minimize
preferences-system-windows-effect-mouseclick
preferences-system-windows-effect-mousemark
preferences-system-windows-effect-presentwindows
preferences-system-windows-effect-resize
preferences-system-windows-effect-scale-in
preferences-system-windows-effect-screenedge
preferences-system-windows-effect-screenshot
preferences-system-windows-effect-showfps
preferences-system-windows-effect-showpaint
preferences-system-windows-effect-slide
preferences-system-windows-effect-slideback
preferences-system-windows-effect-slidingpopups
preferences-system-windows-effect-startupfeedback
preferences-system-windows-effect-thumbnailaside
preferences-system-windows-effect-trackmouse
preferences-system-windows-effect-translucency
preferences-system-windows-effect-windowaperture
preferences-system-windows-effect-wobblywindows
preferences-system-windows-effect-zoom
preferences-system-windows-move
preferences-tabs
preferences-virtualization-container
preferences-virtualization-vm
preferences-virtualization-vm-install
preferences-virtualization-vm-migrate
preferences-virtualization-vm-new
preferences-web-browser-adblock
preferences-web-browser-cache
preferences-web-browser-cookies
preferences-web-browser-identification
preferences-web-browser-shortcuts
preferences-web-browser-ssl
preferences-web-browser-stylesheets
preflight-verifier
PrePostCondition
presence_away
presence_offline
presence_online
presence_unknown
prevfuzzy
prevfuzzyuntrans
preview
preview-add-zone
preview_math
preview-remove-all
preview-remove-zone
preview-render-off
preview-render-on
preview_sel
prevuntranslated
primarykey_constraint
printer
printer-error-symbolic
printer-network-symbolic
printer-printing-symbolic
printer-symbolic
printer-warning-symbolic
process-stop
process-stop-symbolic
process-working
process-working-symbolic
project_add
project_archive
project-defaults
project-development
project-development-close
project-development-close-all
project-development-new-template
projectgrep
project-open
project_rebuild
project_remove
project_show
ps2pdf
puremaps
pythonbackend
q4wine
qa
qalculate
qbittorrent
qdbusviewer
qelectrotech
QOwnNotes
qtcreator
QtProject-designer
quassel
question
quick
quickopen
quickopen-class
quickopen-file
quickopen-function
quickview
quickwizard
quiterss
qupzilla
r
radio
raindrop
randomize
rating
rating-half
rating-half-rtl
rating-unrated
ratiocrop
rbackend
realization
rectangle-make-corners-sharp
rectangle-shape
redeyes
redshift-status-day
redshift-status-off
redshift-status-on
refactor
refreshstructure
region
rekonq
relation
relationship
remove
remove-amarok
removecell
remove-link
repeat
repository
resizecol
resizerow
resource-calendar-child
resource-calendar-child-insert
resource-calendar-insert
resource-group
resource-group-new
restoration
retweet
reverse
ring
ring-kde
rocs
roll
rosegarden
rotation-allowed
rotation-allowed-symbolic
rotation-locked-landscape
rotation-locked-landscape-symbolic
rotation-locked-portrait
rotation-locked-portrait-symbolic
rotation-locked-symbolic
routeplanning
rss
run-build
run-build-clean
run-build-configure
run-build-file
run-build-install
run-build-install-root
run-build-prune
run-clean
run-install
sagebackend
sage-notebook
scanner
scribus
script-error
scriptnew
scriptopen
search
secure-card
security-high
security-high-symbolic
security-low
security-low-symbolic
security-medium
security-medium-symbolic
select
selection
selection-bottom
selection-end-symbolic
selection-end-symbolic-rtl
selection-lower
selection-make-bitmap-copy
selection-move-to-layer-above
selection-move-to-layer-below
selection-raise
selection-start-symbolic
selection-start-symbolic-rtl
selection-top
select-rectangular
semi-starred-symbolic
semi-starred-symbolic-rtl
send_signal
send-to-symbolic
server-database
services
set-language
settings-configure
shallow-history
shape-choose
shape-cuboid
shapes
sharedlib
sharpenimage
shear
sheets
show-all-effects
show-dialogs
showfoto
show-gpu-effects
show-grid
show-guides
show-menu
show-node-handles
show-offline
show-path-outline
show_table_column
show_table_row
shuffle
sidebar-collapse
sidebar-collapse-left
sidebar-collapse-right
sidebar-expand
sidebar-expand-left
sidebar-expand-right
sidebar-show-symbolic
similarartists-amarok
skanlite
skanpage
skg-chart-bubble
skrooge
skrooge-black
skrooge_credit_card
skrooge-initial
skrooge_less
skrooge_more
skrooge_much_less
skrooge_much_more
skrooge_type
slanted
smallclock
smallfrac
smallskip
smartgit
smartnewline
smartphone
smb4k
smiley
smiley-add
smiley-shape
smooth
smplayer
smtube
snap
snap-angle
snap-bounding-box
snap-bounding-box-center
snap-bounding-box-corners
snap-bounding-box-edges
snap-bounding-box-midpoints
snap-extension
snap-grid-guide-intersections
snap-guideline
snap-intersection
snap-node
snap-nodes-center
snap-nodes-cusp
snap-nodes-intersection
snap-nodes-midpoint
snap-nodes-path
snap-nodes-rotation-center
snap-nodes-smooth
snap-orthogonal
snap-page
snap-text-baseline
social
sort_incr
sort-name
sort-presence
source-playlist
source-smart-playlist
speaker
special-effects-symbolic
special_paste
specific-setup
spectacle
speedometer
spiral-shape
split
spreadsheetshape
sqrt
stage
standard-connector
star-new-symbolic
starred-symbolic
star-shape
start-here-branding
start-here-kde
start-here-kde-plasma
start-here-symbolic
start-over
state-download
state-error
state-fork
state-information
state-offline
state-ok
state-pause
stateshape
state-sync
statetool
state-warning
steam
step
step_object_Anchor
step_object_Box
step_object_ChargedParticle
step_object_CircularMotor
step_object_Controller
step_object_CoulombForce
step_object_Disk
step_object_Gas
step_object_GasParticle
step_object_Graph
step_object_GravitationForce
step_object_LinearMotor
step_object_Meter
step_object_Note
step_object_Particle
step_object_Pin
step_object_Polygon
step_object_Rope
step_object_SoftBody
step_object_Spring
step_object_Stick
step_object_Tracer
step_object_WeightForce
stickers
sticky_zoom
stock_folder
story-editor
straight-connector
stroke-cap-bevel
stroke-cap-butt
stroke-cap-miter
stroke-cap-round
stroke-cap-square
stroke-join-bevel
stroke-join-miter
stroke-join-round
stroke-to-path
strong
structure
sublime-merge
sublime-text
subsystem
subtitlecomposer
svn-commit
svn-update
swap-panels
sweeper
symboleditor
symbols
synaptic
syncthing
synfig_icon
system-file-manager
system-help
system-hibernate
system-lock-screen
system-lock-screen-symbolic
system-log-out
system-log-out-rtl
system-reboot
system-run
system-run-symbolic
system-save-session
system-search
system-search-symbolic
systemsettings
system-shutdown
system-shutdown-symbolic
system-software-install
system-software-update
system-suspend
system-suspend-hibernate
system-switch-user
system-upgrade
system-users
tab-close
tab-close-other
tab-detach
tab-duplicate
table
tablet
tab-new
tab-new-background
tab-new-symbolic
tag
tag-addressbook
tag-assigned
tag-delete
tag-edit
tag-events
tag-folder
tag-new
tag-people
tag-places
tag-properties
tag-recents
tag-reset
tag-symbolic
task-complete
task-new
task-process-0
task-process-1
task-process-2
task-process-3
task-process-4
task-recurring
task-reminder
taxes-finances
teamviewer
TeamViewer
telegram
telegram-attention-panel
telegram-mute-panel
telegram-panel
telepathy-kde
temperature-cold
temperature-normal
temperature-warm
template
texcompiler
texlion
texstudio
text-calendar
text-convert-to-regular
text-csharp
text-css
text-csv
text-directory
text-dockerfile
text-enriched
text-field
text-field-framed
text-field-frameless
text-flow-into-frame
text-fortran
text-frame-link
text-frame-unlink
text_horz_kern
text-html
text-javascript
text_letter_spacing
text_line_spacing
text-markdown
text-plain
text-put-on-path
text-rdf
text-rdf+xml
text-remove-from-path
text_remove_kerns
text_rotation
text-rtf
text-rust
text-sgml
text-speak
text_subscript
text_superscript
text-troff
text-unflow
text-unkern
texture
text-vcalendar
text_vert_kern
text-vnd.abc
text-vnd.kde.kcrash-report
text-vnd.trolltech.linguist
text-vnd.wap.wml
text-vtt
text-wiki
text_word_spacing
text-wrap
text-x-adasrc
text-x-apport
text-x-authors
text-x-bibtex
text-x-changelog
text-x-c++hdr
text-x-chdr
text-x-cmake
text-x-copying
text-x-credits
text-x-csharp
text-x-c++src
text-x-csrc
text-x-dtd
text-x-fortran
text-x-generic
text-x-generic.svapplication-x-awk
text-x-gettext-translation
text-x-go
text-x-haskell
text-x-hex
text-x-install
text-x-java
text-x-javascript
text-x-java-source
text-x-katefilelist
text-x-kotlin
text-x-ldif
text-x-lilypond
text-x-log
text-x-lua
text-x-makefile
text-x-markdown
text-xmcd
text-x-microdvd
text-xml
text-x-mpsub
text-x-nfo
text-x-objchdr
text-x-objcsrc
text-x-opml
text-x-opml+xml
text-x-pascal
text-x-patch
text-x-plain
text-x-po
text-x-python
text-x-python3
text-x-qml
text-x-r
text-x-readme
text-x-rpm-spec
text-x-rust
text-x-sass
text-x-scala
text-x-script
text-x-scss
text-x-sql
text-x-ssa
text-x-subviewer
text-x-tcl
text-x-tex
text-x-texinfo
text-x-vcard
text-x-xslfo
timeline-extract
timeline-insert
timeline-lift
timeline-overwrite
timeline-use-zone-off
timeline-use-zone-on
tool-animator
tool_brush
tool_cellformatting
tool_color_eraser
tool_color_picker
tool_curve
tool_ellipse
tool_elliptical_selection
tool_eraser
tool_flood_fill
tool_free_form_selection
tool_imageeffects
tool_line
tool-measure
tool-node-editor
tool_pagelayout
tool_pen
tool-pointer
tool_polygon
tool_polyline
tool_rectangle
tool_rect_selection
tool_references
tool_review
tool_rounded_rectangle
tools
tools-check-spelling
tools-check-spelling-symbolic
tools-media-optical-burn
tools-media-optical-burn-image
tools-media-optical-copy
tools-media-optical-erase
tools-media-optical-format
tool-spray
tool_spraycan
tools-report-bug
tools-rip-audio-cd
tools-rip-video-cd
tools-rip-video-dvd
tools-symbolic
tools-wizard
tool-text
tool_text
tool-tweak
torrents
transform-affect-gradient
transform-affect-pattern
transform-affect-rounded-corners
transform-affect-stroke
transform-browse
transform-crop
transform-crop-and-resize
transform-move
transform-move-horizontal
transform-move-vertical
transform-rotate
transform-scale
transform-scale-horizontal
transform-scale-textbox-points
transform-scale-vertical
transform-shear-down
transform-shear-left
transform-shear-right
transform-shear-up
transform-skew-horizontal
transform-skew-vertical
transmission-tray-icon
transsearch
trash-empty
trim-margins
trim-to-selection
truecrypt
tv
typewriter
uav
uav-quadcopter
ubiquity
ubiquity-kde
umbr-coll-message-asynchronous
umbr-coll-message-synchronous
umbrello
umbrello_diagram_activity
umbrello_diagram_class
umbrello_diagram_collaboration
umbrello_diagram_component
umbrello_diagram_deployment
umbrello_diagram_entityrelationship
umbrello_diagram_sequence
umbrello_diagram_state
umbrello_diagram_usecase
umbr-message-asynchronous
umbr-message-found
umbr-message-lost
umbr-message-synchronous
underexposure
unetbootin
uniassociation
uninstall
unique_constraint
unknown
unlock
unmarkasblank
unrequired
upcomingevents-amarok
update-high
update-low
update-medium
update-none
upindicator
upload-media
uri-mms
uri-mmst
uri-pnm
uri-rtspt
uri-rtspu
usb-creator-kde
usecase
user
user-ada-lovelace
user-alice-in-wonderland
user-available
user-available-symbolic
user-away
user-away-extended
user-away-symbolic
user-bookmarks-symbolic
user-busy
user-busy-symbolic
user-desktop
user-desktop-symbolic
user-grace-hopper
user-group-delete
user-group-new
user-group-properties
user-home
user-home-symbolic
user-identity
user-idle
user-idle-symbolic
user-invisible
user-invisible-symbolic
user-leonardo-da-vinci
user-mahatma-gandhi
user-man
usermenu-delete
usermenu-down
usermenu-up
user-mowgli
username-copy
user-none
user-not-tracked-symbolic
user-offline
user-offline-symbolic
user-online
user-others
user-properties
user-status-pending-symbolic
user-trash
user-trash-full
user-trash-full-symbolic
user-trash-symbolic
utilities-energy-monitor
utilities-file-archiver
utilities-log-viewer
utilities-system-monitor
utilities-terminal
VBox
vcs-added
vcs-branch
vcs-branch-delete
vcs-commit
vcs-commit-cvs-cervisia
vcs-conflicting
vcs-diff
vcs-diff-cvs-cervisia
vcs-locally-modified
vcs-locally-modified-unstaged
vcs-merge
vcs-merge-request
vcs-normal
vcs-pull
vcs-push
vcs-remove-cvs-cervisia
vcs-removed
vcs-stash
vcs-stash-pop
vcs-status-cvs-cervisia
vcs-update-cvs-cervisia
vcs-update-required
veracrypt
verb
verbatim
viber
video-card-inactive
videoclip-amarok
video-display
video-mlt-playlist
video-mp2t
video-mp4
video-television
video-vivo
video-vnd.rn-realvideo
video-wavelet
video-webm
video-x-anim
video-x-flic
video-x-flv
video-x-generic
video-x-google-vlc-plugin
video-x-javafx
video-x-matroska
video-x-mng
video-x-msvideo
video-x-ms-wmp
video-x-ms-wmv
video-x-ogm+ogg
video-x-theora+ogg
video-x-wmv
view-app-grid-symbolic
view-bank
view-bank-add
view-bank-delete
view-bank-edit
view-barcode
view-barcode-add
view-barcode-qr
viewbib
view-calendar
view-calendar-agenda
view-calendar-birthday
view-calendar-day
view-calendar-holiday
view-calendar-journal
view-calendar-list
view-calendar-month
view-calendar-special-occasion
view-calendar-tasks
view-calendar-timeline
view-calendar-time-spent
view-calendar-upcoming-days
view-calendar-upcoming-events
view-calendar-wedding-anniversary
view-calendar-week
view-calendar-whatsnext
view-calendar-workweek
view-catalog
view-categories-expenditures
view-categories-incomes
view-certificate
view-certificate-add
view-certificate-export
view-certificate-export-secret
view-certificate-export-server
view-certificate-import
view-certificate-server-configure
view-certificate-sign
view-choose
view-close
view-continuous-symbolic
view-conversation-balloon
view-currency-list
view-dual-symbolic
viewdvi
view-file-columns
view-filter
view-financial-account
view-financial-account-add
view-financial-account-asset
view-financial-account-asset-closed
view-financial-account-cash
view-financial-account-cash-closed
view-financial-account-checking
view-financial-account-checking-closed
view-financial-account-close
view-financial-account-closed
view-financial-account-credit-card
view-financial-account-credit-card-closed
view-financial-account-delete
view-financial-account-edit
view-financial-account-investment
view-financial-account-investment-closed
view-financial-account-investment-security
view-financial-account-investment-security-closed
view-financial-account-liability
view-financial-account-liability-closed
view-financial-account-loan
view-financial-account-loan-closed
view-financial-account-reopen
view-financial-account-savings
view-financial-account-savings-closed
view-financial-budget
view-financial-category
view-financial-category-add
view-financial-category-delete
view-financial-category-edit
view-financial-category-expense
view-financial-category-income
view-financial-list
view-financial-transfer-reconcile
view-financial-transfer-reconciled
view-financial-transfer-unreconciled
view_fit_to_page
view-form
view-form-action
view-fullscreen
view-fullscreen-symbolic
view-grid
view-grid-symbolic
view-group
view-hidden
view-history
viewhtml
viewimage
view-institution
view-institution-add
view-institution-delete
view-institution-edit
view-left-close
view-left-new
view-list-details
view-list-icons
view-list-symbolic
view-list-text
view-list-tree
viewlog
view-media-album-cover
view-media-artist
view-media-chart
view-media-config
view-media-equalizer
view-media-favorite
view-media-genre
view-media-lyrics
view-media-playcount
view-media-playlist
view-media-publisher
view-media-recent
view-media-similarartists
view-media-title
view-media-track
view-media-visualization
view-more-horizontal-symbolic
view-more-symbolic
view-multiple-objects
view-object-histogram-linear
view-object-histogram-logarithmic
view-pages-continuous
view-pages-facing
view-pages-facing-first-centered
view-pages-overview
view-pages-single
viewpdf
view-pim-calendar
view-pim-contacts
view-pim-journal
view-pim-mail
view-pim-news
view-pim-notes
view-pim-tasks
view-pim-tasks-pending
view-presentation
view-presentation-symbolic
view-preview
view-private
view-private-symbolic
view-process-all
view-process-all-tree
view-process-own
view-process-system
view-process-tree
view-process-users
viewps
view-readermode
view-readermode-active
view-refresh
view-refresh-symbolic
view-resource-calendar
view-restore
view-restore-symbolic
view-right-close
view-right-new
view-services-scripted-amarok
view-sidetree
view-sort
view-sort-ascending
view-sort-ascending-name
view-sort-ascending-symbolic
view-sort-descending
view-sort-descending-name
view-sort-descending-symbolic
view-split-effect
view-split-left-right
view-split-top-bottom
view-statistics
view-table-of-contents-ltr
view-table-of-contents-rtl
view-task
view-task-add
view-task-child
view-task-child-add
view-tasks-all-symbolic
view-tasks-today-symbolic
view-tasks-unscheduled-symbolic
view-tasks-week-symbolic
view-time-schedule
view-time-schedule-baselined
view-time-schedule-baselined-add
view-time-schedule-baselined-remove
view-time-schedule-calculus
view-time-schedule-child-insert
view-time-schedule-edit
view-time-schedule-insert
view-unsplit-effect
view-visible
view-web-browser-dom-tree
view-wrapped-symbolic
view-wrapped-symbolic-rtl
view-zoom-fit-height-symbolic
view-zoom-fit-symbolic
view-zoom-fit-width-symbolic
view-zoom-in-symbolic
view-zoom-original-symbolic
view-zoom-out-symbolic
virt-manager
virtualbox
virtualbox-hdd
virtualbox-ova
virtualbox-ovf
virtualbox-vbox
virtualbox-vbox-extpack
virtualbox-vdi
virtualbox-vhd
virtualbox-vmdk
virtual-desktops
visibility
vlc
vnd.ms-publisher
vokoscreen
vvave
wallet-closed
wallet-open
warnnext
warnprev
wayland
weather-clear
weather-clear-night
weather-clear-wind
weather-clear-wind-night
weather-clouds
weather-clouds-night
weather-clouds-wind
weather-clouds-wind-night
weather-few-clouds
weather-few-clouds-night
weather-few-clouds-wind
weather-few-clouds-wind-night
weather-fog
weather-freezing-rain
weather-hail
weather-many-clouds
weather-many-clouds-wind
weather-mist
weather-none-available
weather-overcast
weather-overcast-wind
weather-showers
weather-showers-day
weather-showers-night
weather-showers-scattered
weather-showers-scattered-day
weather-showers-scattered-night
weather-snow
weather-snow-rain
weather-snow-scattered
weather-snow-scattered-day
weather-snow-scattered-night
weather-storm
weather-storm-day
weather-storm-night
webcam
whitebalance
widget-alternatives
window
window-close
window-close-symbolic
window-duplicate
window-keep-above
window-keep-above-symbolic
window-keep-below
window-keep-below-symbolic
window-maximize
window-maximize-symbolic
window-minimize
window-minimize-symbolic
window-new
window-next
window-pin
window-pin-symbolic
window-previous
window-restore
window-restore-symbolic
window-shade
window-shade-symbolic
window-unpin
window-unpin-symbolic
window-unshade
window-unshade-symbolic
wine
wizard_math
wizard_pdftools
wizard_pstools
wizard_tabular
words
xchat
x-clementine-album
x-clementine-albums
x-clementine-artist
x-clementine-shuffle
xfsm-hibernate
xine
x-kde-nsplugin-generated
x-mail-distribution-list
x-media-podcast
xmind
xml-attribute-delete
xml-element-new
xml-node-delete
xml-node-duplicate
xml-text-new
x-office-address-book
x-office-calendar
x-office-contact
x-office-document
x-office-drawing
x-office-presentation
x-office-spreadsheet
xorg
x-shape-connection
x-shape-formula
x-shape-image
x-shape-text
xterm
xterm-color
x-zoom-in
x-zoom-out
yakuake
yandex-browser
yast
yast-addon
yast-addon-extension
yast-alternatives
yast-apparmor
yast-auth-client
yast-autoyast
yast-bootloader
yast-checkmedia
yast-control-center
yast-create-new-vm
yast-device-tree
yast-dhcp-server
yast-disk
yast-dns-server
yast-docker
yast-dsl
yast-fcoe
yast-firewall
yast-fonts
yast-ftp-server
yast-hardware-group
yast-host
yast-http-server
yast-hwinfo
yast-installation
yast-instserver
yast-iscsi-client
yast-iscsi-server
yast-journal
yast-kerberos-server
yast-kernel
yast-keyboard
yast-lan
yast-language
yast-ldap-kerberos
yast-ldap-server
yast-mail
yast-messages
yast-misc-group
yast-network-group
yast-nfs
yast-nfs-server
yast-nis
yast-nis-server
yast-ntp-client
yast-printer
yast-proxy
yast-release-notes
yast-remote
yast-samba-client
yast-samba-server
yast-scanner
yast-security
yast-security-group
yast-services-manager
yast-slp-server
yast-snapper
yast-software
yast-software-group
yast-sound
yast-sudo
yast-support
yast-support-group
yast-sw_single
yast-sw_source
yast-sysconfig
yast-system-group
yast-tftp-server
yast-timezone
yast-update
yast-update-online
yast-update-online-configuration
yast-upgrade
yast-users
yast-vm-group
yast-vm-install
yast-vm-migrate
yast-vpn
yast-wol
y-zoom-in
y-zoom-out
zanshin
zone-in
zone-out
zoom
zoom-1-to-2
zoom-2-to-1
zoom-all
zoom-double-size
zoom-draw
zoom-fit-best
zoom-fit-best-symbolic
zoom-fit-drawing
zoom-fit-height
zoom-fit-page
zoom-fit-selection
zoom-fit-width
zoom-half-size
zoom-in
zoom-in-large
zoom-in-symbolic
zoom-in-x
zoom-in-y
zoom-next
zoom-original
zoom-original-symbolic
zoom-out
zoom-out-large
zoom-out-symbolic
zoom-out-x
zoom-out-y
zoom-pixels
zoom-previous
zoom-select
zoom-select-fit
zoom-selection
zoom-select-x
zoom-select-y
kleopatra
okular"

#set -x

rm -f /tmp/findicons
for icon in $ICONS; do
    if grep -q -r QIcon::fromTheme.\*\(\"$icon "$1" ||
       grep -q -r addPage.\*\(\"$icon "$1"; then
        if grep -q $icon `dirname $0`/../src/inst-breeze-icons.nsi; then
            echo -n ""
        else
            find /usr/share/icons/breeze -name $icon.svg >> /tmp/findicons
        fi
    fi
done

if [ ! -e /tmp/findicons ]; then
    echo "No new icons found"
    exit 0
fi

sed 's@/usr@  File \${prefix\}@' -i /tmp/findicons
echo "# Files for installer, please sort into sections"
cat /tmp/findicons | sort -u

echo "# Files for uninstaller, please sort into sections"
sed 's@File \${prefix\}@Delete "\$INSTDIR@' -i /tmp/findicons
sed 's@$@"@' -i /tmp/findicons
sed 's@/@\\@g' -i /tmp/findicons
cat /tmp/findicons | sort -u
