#!/bin/sh
# Script to generate teh checksums for a release.

version="$1"
if [ -z "$version" ]; then
  echo "usage: mk-chksums VERSION" >&2
  exit 1
fi

for i in gpg4win-$version.tar.bz2 gpg4win-$version.exe \
         gpg4win-src-$version.exe ; do
  if [ ! -f "$i" ]; then
    echo "mk-chksums: file $i is missing in current directory" >&2
    exit 1
  fi
done

sha1_src="`sha1sum gpg4win-$version.tar.bz2 | awk '{print $1}'`"
sha1_exe="`sha1sum gpg4win-$version.exe | awk '{print $1}'`"
sha1_exs="`sha1sum gpg4win-src-$version.exe | awk '{print $1}'`"
sha2_src="`sha256sum gpg4win-$version.tar.bz2 | awk '{print $1}'`"
sha2_exe="`sha256sum gpg4win-$version.exe | awk '{print $1}'`"
sha2_exs="`sha256sum gpg4win-src-$version.exe | awk '{print $1}'`"
len_src="`ls -l  gpg4win-$version.tar.bz2 | awk '{print $5}'`"
len_exe="`ls -l  gpg4win-$version.exe | awk '{print $5}'`"
len_exs="`ls -l  gpg4win-src-$version.exe | awk '{print $5}'`"


cat <<EOF
m4_define(\`SHA1_SRC',\`$sha1_src')
m4_define(\`SHA1_EXE',\`$sha1_exe')
m4_define(\`SHA1_EXS',\`$sha1_exs')
m4_define(\`SHA2_SRC',\`$sha2_src')
m4_define(\`SHA2_EXE',\`$sha2_exe')
m4_define(\`SHA2_EXS',\`$sha2_exs')
m4_define(\`LEN_SRC',\`$len_src')
m4_define(\`LEN_EXE',\`$len_exe')
m4_define(\`LEN_EXS',\`$len_exs')
EOF

echo "############# SWDB Snippet"
pref="#+macro: gpg4win_"
reldate="$(date -u +%Y-%m-%d)"
echo "${pref}ver  $version"
echo "${pref}date ${reldate}"
echo "${pref}src_size $(wc -c < gpg4win-$version.tar.bz2 |awk '{print int($1/1024)}')k"
echo "${pref}src_sha1 $sha1_src"
echo "${pref}src_sha2 $sha2_src"
echo "${pref}exe_size $(wc -c < gpg4win-$version.exe |awk '{print int($1/1024)}')k"
echo "${pref}exe_sha1 $sha1_exe"
echo "${pref}exe_sha2 $sha2_exe"
echo "${pref}isrc_size $(wc -c < gpg4win-src-$version.exe |awk '{print int($1/1024)}')k"
echo "${pref}isrc_sha1 $sha1_exs"
echo "${pref}isrc_sha2 $sha2_exs"
echo "############# END SWDB Snippet"
